/**
 * 汉语拼音全量基础音节与组词库
 * 包含 23 个声母 × 24 个韵母 × 4 个声调的常用字词映射与标准小学拼读语音文本
 */

export const shengmuNames = {
  'b': '玻', 'p': '坡', 'm': '摸', 'f': '佛',
  'd': '得', 't': '特', 'n': '讷', 'l': '勒',
  'g': '哥', 'k': '科', 'h': '喝',
  'j': '鸡', 'q': '七', 'x': '西',
  'zh': '知', 'ch': '吃', 'sh': '诗', 'r': '日',
  'z': '资', 'c': '疵', 's': '思',
  'y': '衣', 'w': '屋'
}

export const yunmuNames = {
  'a': '啊', 'o': '喔', 'e': '鹅', 'i': '衣', 'u': '乌', 'ü': '迂',
  'ai': '挨', 'ei': '欸', 'ui': '威', 'ao': '奥', 'ou': '欧', 'iu': '优',
  'ie': '椰', 'üe': '约', 'er': '儿',
  'an': '安', 'en': '恩', 'in': '因', 'un': '温', 'ün': '晕',
  'ang': '昂', 'eng': '鞥', 'ing': '英', 'ong': '轰'
}

export const toneNamesMap = {
  1: '第一声', 2: '第二声', 3: '第三声', 4: '第四声'
}

export const toneMap = {
  'a': ['ā', 'á', 'ǎ', 'à'],
  'o': ['ō', 'ó', 'ǒ', 'ò'],
  'e': ['ē', 'é', 'ě', 'è'],
  'i': ['ī', 'í', 'ǐ', 'ì'],
  'u': ['ū', 'ú', 'ǔ', 'ù'],
  'ü': ['ǖ', 'ǘ', 'ǚ', 'ǜ'],
  'ai': ['āi', 'ái', 'ǎi', 'ài'],
  'ei': ['ēi', 'éi', 'ěi', 'èi'],
  'ui': ['uī', 'uí', 'uǐ', 'uì'],
  'ao': ['āo', 'áo', 'ǎo', 'ào'],
  'ou': ['ōu', 'óu', 'ǒu', 'òu'],
  'iu': ['iū', 'iú', 'iǔ', 'iù'],
  'ie': ['iē', 'ié', 'iě', 'iè'],
  'üe': ['üē', 'üé', 'üě', 'üè'],
  'an': ['ān', 'án', 'ǎn', 'àn'],
  'en': ['ēn', 'én', 'ěn', 'èn'],
  'in': ['īn', 'ín', 'ǐn', 'ìn'],
  'un': ['ūn', 'ún', 'ǔn', 'ùn'],
  'ün': ['ǖn', 'ǘn', 'ǚn', 'ǜn'],
  'ang': ['āng', 'áng', 'ǎng', 'àng'],
  'eng': ['ēng', 'éng', 'ěng', 'èng'],
  'ing': ['īng', 'íng', 'ǐng', 'ìng'],
  'ong': ['ōng', 'óng', 'ǒng', 'òng'],
}

// 全量常用拼音字词库（覆盖几乎所有小学常用字）
export const pinyinMasterDict = {
  // b
  'b-a-1': { pinyin: 'bā', hanzi: '八 · 芭蕉 · 扒开', sample: '八，八个的八' },
  'b-a-2': { pinyin: 'bá', hanzi: '拔萝卜 · 拔河', sample: '拔，拔萝卜的拔' },
  'b-a-3': { pinyin: 'bǎ', hanzi: '把手 · 火把', sample: '把，火把的把' },
  'b-a-4': { pinyin: 'bà', hanzi: '爸爸 · 大坝', sample: '爸，爸爸的爸' },
  'b-o-1': { pinyin: 'bō', hanzi: '菠萝 · 广播 · 波浪', sample: '波，菠萝的波' },
  'b-o-2': { pinyin: 'bó', hanzi: '伯伯 · 停泊', sample: '伯，伯伯的伯' },
  'b-o-3': { pinyin: 'bǒ', hanzi: '跛脚', sample: '跛' },
  'b-o-4': { pinyin: 'bò', hanzi: '薄荷', sample: '薄，薄荷的薄' },
  'b-i-1': { pinyin: 'bī', hanzi: '逼真 · 逼近', sample: '逼' },
  'b-i-2': { pinyin: 'bí', hanzi: '鼻子 · 鼻涕', sample: '鼻，鼻子的鼻' },
  'b-i-3': { pinyin: 'bǐ', hanzi: '铅笔 · 比赛', sample: '笔，铅笔的笔' },
  'b-i-4': { pinyin: 'bì', hanzi: '手臂 · 关门(闭)', sample: '臂，手臂的臂' },
  'b-u-3': { pinyin: 'bǔ', hanzi: '补充 · 缝补', sample: '补，补充的补' },
  'b-u-4': { pinyin: 'bù', hanzi: '不要 · 跑步 · 步步高', sample: '不，不要的不' },
  'b-ai-1': { pinyin: 'bāi', hanzi: '掰开 · 掰玉米', sample: '掰，掰开的掰' },
  'b-ai-2': { pinyin: 'bái', hanzi: '白色 · 白天 · 小白兔', sample: '白，白色的白' },
  'b-ai-3': { pinyin: 'bǎi', hanzi: '一百 · 摆动', sample: '百，一百的百' },
  'b-ai-4': { pinyin: 'bài', hanzi: '拜年 · 拜拜', sample: '拜，拜年的拜' },
  'b-ei-1': { pinyin: 'bēi', hanzi: '水杯 · 背包', sample: '杯，水杯的杯' },
  'b-ei-3': { pinyin: 'běi', hanzi: '北京 · 北方', sample: '北，北京的北' },
  'b-ei-4': { pinyin: 'bèi', hanzi: '被子 · 宝贝 · 背后', sample: '被，被子的被' },
  'b-ao-1': { pinyin: 'bāo', hanzi: '书包 · 面包', sample: '包，面包的包' },
  'b-ao-2': { pinyin: 'báo', hanzi: '薄饼 · 冰雹', sample: '雹，冰雹的雹' },
  'b-ao-3': { pinyin: 'bǎo', hanzi: '吃饱 · 保护 · 宝宝', sample: '宝，宝宝的宝' },
  'b-ao-4': { pinyin: 'bào', hanzi: '抱抱 · 报纸', sample: '抱，抱抱的抱' },
  'b-an-1': { pinyin: 'bān', hanzi: '班级 · 搬家', sample: '班，班级的班' },
  'b-an-3': { pinyin: 'bǎn', hanzi: '黑板 · 木板', sample: '板，黑板的板' },
  'b-an-4': { pinyin: 'bàn', hanzi: '一半 · 办法 · 伙伴', sample: '办，办法的办' },
  'b-en-1': { pinyin: 'bēn', hanzi: '奔跑 · 奔驰', sample: '奔，奔跑的奔' },
  'b-en-3': { pinyin: 'běn', hanzi: '课本 · 书本', sample: '本，书本的本' },
  'b-en-4': { pinyin: 'bèn', hanzi: '笨笨 · 笨拙', sample: '笨' },
  'b-in-1': { pinyin: 'bīn', hanzi: '宾客 · 彬彬有礼', sample: '宾，宾客的宾' },
  'b-ang-1': { pinyin: 'bāng', hanzi: '帮助 · 帮忙', sample: '帮，帮助的帮' },
  'b-ang-3': { pinyin: 'bǎng', hanzi: '榜样 · 翅膀', sample: '膀，翅膀的膀' },
  'b-ang-4': { pinyin: 'bàng', hanzi: '棒棒糖 · 真棒', sample: '棒，真棒的棒' },
  'b-eng-1': { pinyin: 'bēng', hanzi: '紧绷 · 崩裂', sample: '绷' },
  'b-eng-4': { pinyin: 'bèng', hanzi: '蹦蹦跳跳', sample: '蹦，蹦跳的蹦' },
  'b-ing-1': { pinyin: 'bīng', hanzi: '冰块 · 士兵', sample: '冰，冰块的冰' },
  'b-ing-3': { pinyin: 'bǐng', hanzi: '饼干 · 月饼', sample: '饼，饼干的饼' },
  'b-ing-4': { pinyin: 'bìng', hanzi: '生病 · 并且', sample: '病，生病的病' },

  // p
  'p-a-1': { pinyin: 'pā', hanzi: '趴下 · 趴在桌上', sample: '趴，趴下的趴' },
  'p-a-2': { pinyin: 'pá', hanzi: '爬山 · 爬行', sample: '爬，爬山的爬' },
  'p-a-4': { pinyin: 'pà', hanzi: '害怕 · 不怕', sample: '怕，害怕的怕' },
  'p-o-1': { pinyin: 'pō', hanzi: '泼水 · 山坡', sample: '坡，山坡的坡' },
  'p-o-2': { pinyin: 'pó', hanzi: '婆婆 · 外婆', sample: '婆，外婆的婆' },
  'p-o-4': { pinyin: 'pò', hanzi: '破开 · 破坏', sample: '破，破开的破' },
  'p-i-1': { pinyin: 'pī', hanzi: '批改 · 披风', sample: '披，披风的披' },
  'p-i-2': { pinyin: 'pí', hanzi: '皮球 · 苹果皮', sample: '皮，皮球的皮' },
  'p-i-3': { pinyin: 'pǐ', hanzi: '匹配 · 一匹马', sample: '匹，一匹马的匹' },
  'p-i-4': { pinyin: 'pì', hanzi: '放屁 · 屁股', sample: '屁' },
  'p-u-1': { pinyin: 'pū', hanzi: '铺开 · 扑过去', sample: '扑，扑过去的扑' },
  'p-u-2': { pinyin: 'pú', hanzi: '葡萄 · 蒲公英', sample: '葡，葡萄的葡' },
  'p-u-3': { pinyin: 'pǔ', hanzi: '普通话 · 谱子', sample: '普，普通话的普' },
  'p-u-4': { pinyin: 'pù', hanzi: '瀑布 · 店铺', sample: '瀑，瀑布的瀑' },
  'p-ai-1': { pinyin: 'pāi', hanzi: '拍手 · 拍照', sample: '拍，拍手的拍' },
  'p-ai-2': { pinyin: 'pái', hanzi: '排队 · 门牌', sample: '排，排队的排' },
  'p-ai-4': { pinyin: 'pài', hanzi: '派对 · 气派', sample: '派，派对的派' },
  'p-ei-1': { pinyin: 'pēi', hanzi: '胚芽 · 培养', sample: '胚' },
  'p-ei-2': { pinyin: 'péi', hanzi: '陪伴 · 陪着', sample: '陪，陪伴的陪' },
  'p-ei-4': { pinyin: 'pèi', hanzi: '配合 · 佩服', sample: '配，配合的配' },
  'p-ao-1': { pinyin: 'pāo', hanzi: '抛起 · 抛球', sample: '抛，抛起的抛' },
  'p-ao-2': { pinyin: 'páo', hanzi: '长袍 · 咆哮', sample: '袍' },
  'p-ao-3': { pinyin: 'pǎo', hanzi: '跑步 · 赛跑', sample: '跑，跑步的跑' },
  'p-ao-4': { pinyin: 'pào', hanzi: '气泡 · 大炮 · 泡泡糖', sample: '泡，气泡的泡' },
  'p-ou-1': { pinyin: 'pōu', hanzi: '解剖 · 剖开', sample: '剖' },
  'p-an-1': { pinyin: 'pān', hanzi: '攀登 · 攀爬', sample: '攀，攀爬的攀' },
  'p-an-2': { pinyin: 'pán', hanzi: '盘子 · 棋盘', sample: '盘，盘子的盘' },
  'p-an-4': { pinyin: 'pàn', hanzi: '盼望 · 判断', sample: '盼，盼望的盼' },
  'p-en-1': { pinyin: 'pēn', hanzi: '喷泉 · 喷水', sample: '喷，喷水的喷' },
  'p-en-2': { pinyin: 'pén', hanzi: '花盆 · 脸盆', sample: '盆，花盆的盆' },
  'p-in-1': { pinyin: 'pīn', hanzi: '拼音 · 拼图', sample: '拼，拼音的拼' },
  'p-in-2': { pinyin: 'pín', hanzi: '频繁 · 贫困', sample: '频' },
  'p-in-3': { pinyin: 'pǐn', hanzi: '品德 · 作品 · 品尝', sample: '品，作品的品' },
  'p-ang-2': { pinyin: 'páng', hanzi: '旁边 · 旁人', sample: '旁，旁边的旁' },
  'p-ang-4': { pinyin: 'pàng', hanzi: '胖胖 · 肥胖', sample: '胖，胖胖的胖' },
  'p-eng-1': { pinyin: 'pēng', hanzi: '烹饪 · 砰的一声', sample: '烹' },
  'p-eng-2': { pinyin: 'péng', hanzi: '朋友 · 朋克', sample: '朋，朋友的朋' },
  'p-eng-3': { pinyin: 'pěng', hanzi: '双手捧着', sample: '捧，捧着的捧' },
  'p-eng-4': { pinyin: 'pèng', hanzi: '碰见 · 碰撞', sample: '碰，碰见的碰' },
  'p-ing-1': { pinyin: 'pīng', hanzi: '乒乓球', sample: '乒，乒乓球的乒' },
  'p-ing-2': { pinyin: 'píng', hanzi: '苹果 · 和平 · 瓶子', sample: '苹，苹果的苹' },

  // m
  'm-a-1': { pinyin: 'mā', hanzi: '妈妈 · 妈咪', sample: '妈，妈妈的妈' },
  'm-a-2': { pinyin: 'má', hanzi: '麻烦 · 麻雀', sample: '麻，麻雀的麻' },
  'm-a-3': { pinyin: 'mǎ', hanzi: '小马 · 跑马', sample: '马，小马的马' },
  'm-a-4': { pinyin: 'mà', hanzi: '批评 · 责骂', sample: '骂' },
  'm-o-1': { pinyin: 'mō', hanzi: '摸一摸 · 摸着', sample: '摸，摸摸的摸' },
  'm-o-2': { pinyin: 'mó', hanzi: '魔术 · 蘑菇', sample: '魔，魔术的魔' },
  'm-o-3': { pinyin: 'mǒ', hanzi: '抹布 · 涂抹', sample: '抹，抹布的抹' },
  'm-o-4': { pinyin: 'mò', hanzi: '周末 · 默默', sample: '末，周末的末' },
  'm-e-0': { pinyin: 'me', hanzi: '什么 · 怎么', sample: '么，什么的名' },
  'm-i-1': { pinyin: 'mī', hanzi: '猫咪 · 咪咪叫', sample: '咪，小猫咪的咪' },
  'm-i-2': { pinyin: 'mí', hanzi: '捉迷藏 · 谜语', sample: '迷，捉迷藏的迷' },
  'm-i-3': { pinyin: 'mǐ', hanzi: '大米 · 白米饭', sample: '米，大米的米' },
  'm-i-4': { pinyin: 'mì', hanzi: '蜂蜜 · 秘密', sample: '蜜，蜂蜜的蜜' },
  'm-u-3': { pinyin: 'mǔ', hanzi: '母亲 · 保姆', sample: '母，母亲的母' },
  'm-u-4': { pinyin: 'mù', hanzi: '树木 · 目光', sample: '木，树木的木' },
  'm-ai-2': { pinyin: 'mái', hanzi: '埋藏 · 埋土', sample: '埋' },
  'm-ai-3': { pinyin: 'mǎi', hanzi: '买书 · 买菜', sample: '买，买东西的买' },
  'm-ai-4': { pinyin: 'mài', hanzi: '麦子 · 售卖', sample: '麦，麦子的麦' },
  'm-ei-2': { pinyin: 'méi', hanzi: '草莓 · 没有', sample: '莓，草莓的莓' },
  'm-ei-3': { pinyin: 'měi', hanzi: '美丽 · 美好', sample: '美，美丽的' },
  'm-ei-4': { pinyin: 'mèi', hanzi: '妹妹 · 姐妹', sample: '妹，妹妹的妹' },
  'm-ao-1': { pinyin: 'māo', hanzi: '小猫咪 · 花猫', sample: '猫，小猫的猫' },
  'm-ao-2': { pinyin: 'máo', hanzi: '羽毛 · 毛衣', sample: '毛，羽毛的毛' },
  'm-ao-4': { pinyin: 'mào', hanzi: '帽子 · 礼貌', sample: '帽，帽子的帽' },
  'm-ou-2': { pinyin: 'móu', hanzi: '眸子 · 谋略', sample: '眸' },
  'm-ou-3': { pinyin: 'mǒu', hanzi: '某人 · 某天', sample: '某' },
  'm-ie-1': { pinyin: 'miē', hanzi: '小羊咩咩叫', sample: '咩，小羊叫的咩' },
  'm-ie-4': { pinyin: 'miè', hanzi: '消灭 · 熄灭', sample: '灭，消灭的灭' },
  'm-an-2': { pinyin: 'mán', hanzi: '馒头 · 瞒着', sample: '馒，馒头的馒' },
  'm-an-3': { pinyin: 'mǎn', hanzi: '满满 · 满意', sample: '满，满满的满' },
  'm-an-4': { pinyin: 'màn', hanzi: '慢跑 · 慢慢走', sample: '慢，慢慢的慢' },
  'm-en-1': { pinyin: 'mēn', hanzi: '闷闷不乐 · 闷热', sample: '闷' },
  'm-en-2': { pinyin: 'mén', hanzi: '大门 · 开门', sample: '门，大门的门' },
  'm-in-2': { pinyin: 'mín', hanzi: '人民 · 民族', sample: '民，人民的民' },
  'm-in-3': { pinyin: 'mǐn', hanzi: '敏捷 · 灵敏', sample: '敏，敏捷的敏' },
  'm-ang-2': { pinyin: 'máng', hanzi: '帮忙 · 繁忙', sample: '忙，帮忙的忙' },
  'm-ang-3': { pinyin: 'mǎng', hanzi: '大蟒蛇', sample: '蟒' },
  'm-eng-2': { pinyin: 'méng', hanzi: '萌芽 · 萌萌哒', sample: '萌，萌芽的萌' },
  'm-eng-3': { pinyin: 'měng', hanzi: '猛虎 · 勇敢猛烈', sample: '猛' },
  'm-eng-4': { pinyin: 'mèng', hanzi: '做梦 · 梦想', sample: '梦，梦想的梦' },
  'm-ing-2': { pinyin: 'míng', hanzi: '明亮 · 明天 · 名字', sample: '明，明天的明' },
  'm-ing-4': { pinyin: 'mìng', hanzi: '生命 · 命运', sample: '命，生命的命' },

  // f
  'f-a-1': { pinyin: 'fā', hanzi: '发芽 · 出发 · 发现', sample: '发，发芽的发' },
  'f-a-2': { pinyin: 'fá', hanzi: '竹筏 · 处罚', sample: '筏，竹筏的筏' },
  'f-a-3': { pinyin: 'fǎ', hanzi: '方法 · 办法', sample: '法，办法的法' },
  'f-a-4': { pinyin: 'fà', hanzi: '头发 · 理发', sample: '发，头发的发' },
  'f-o-2': { pinyin: 'fó', hanzi: '大佛 · 乐山大佛', sample: '佛，大佛的佛' },
  'f-u-1': { pinyin: 'fū', hanzi: '皮肤 · 孵蛋', sample: '肤，皮肤的肤' },
  'f-u-2': { pinyin: 'fú', hanzi: '福气 · 祝福 · 衣服', sample: '福，福气的福' },
  'f-u-3': { pinyin: 'fǔ', hanzi: '抚摸 · 斧头', sample: '抚，抚摸的抚' },
  'f-u-4': { pinyin: 'fù', hanzi: '父亲 · 丰富', sample: '父，父亲的父' },
  'f-ei-1': { pinyin: 'fēi', hanzi: '飞机 · 飞翔', sample: '飞，飞机的飞' },
  'f-ei-2': { pinyin: 'féi', hanzi: '肥胖 · 肥皂', sample: '肥，肥皂的肥' },
  'f-ei-3': { pinyin: 'fěi', hanzi: '翡翠 · 土匪', sample: '翡，翡翠的翡' },
  'f-ei-4': { pinyin: 'fèi', hanzi: '免费 · 花费', sample: '费，免费的费' },
  'f-ou-3': { pinyin: 'fǒu', hanzi: '否定 · 是否', sample: '否，否定的否' },
  'f-an-1': { pinyin: 'fān', hanzi: '翻书 · 帆船', sample: '帆，帆船的帆' },
  'f-an-2': { pinyin: 'fán', hanzi: '平凡 · 烦恼', sample: '凡，平凡的凡' },
  'f-an-3': { pinyin: 'fǎn', hanzi: '返回 · 反对', sample: '反，返回的反' },
  'f-an-4': { pinyin: 'fàn', hanzi: '吃饭 · 米饭', sample: '饭，米饭的饭' },
  'f-en-1': { pinyin: 'fēn', hanzi: '分开 · 分享 · 分数', sample: '分，分享的分' },
  'f-en-3': { pinyin: 'fěn', hanzi: '粉色 · 面粉', sample: '粉，粉色的粉' },
  'f-en-4': { pinyin: 'fèn', hanzi: '一份 · 努力奋斗', sample: '份' },
  'f-ang-1': { pinyin: 'fāng', hanzi: '方向 · 正方形', sample: '方，方向的方' },
  'f-ang-2': { pinyin: 'fáng', hanzi: '房子 · 房间', sample: '房，房子的房' },
  'f-ang-3': { pinyin: 'fǎng', hanzi: '访问 · 仿佛', sample: '访' },
  'f-ang-4': { pinyin: 'fàng', hanzi: '放学 · 放风筝', sample: '放，放学的放' },
  'f-eng-1': { pinyin: 'fēng', hanzi: '春风 · 蜜蜂 · 刮风', sample: '风，春风的风' },
  'f-eng-2': { pinyin: 'féng', hanzi: '缝补 · 重逢', sample: '逢' },
  'f-eng-3': { pinyin: 'fěng', hanzi: '讽刺', sample: '讽' },
  'f-eng-4': { pinyin: 'fèng', hanzi: '凤梨 · 凤凰', sample: '凤，凤凰的凤' },

  // d
  'd-a-1': { pinyin: 'dā', hanzi: '搭积木 · 答应', sample: '搭，搭积木的搭' },
  'd-a-2': { pinyin: 'dá', hanzi: '回答 · 达到', sample: '达，回答的答' },
  'd-a-3': { pinyin: 'dǎ', hanzi: '打球 · 打鼓', sample: '打，打球的打' },
  'd-a-4': { pinyin: 'dà', hanzi: '大象 · 大人 · 大海', sample: '大，大象的大' },
  'd-e-2': { pinyin: 'dé', hanzi: '得到 · 德育', sample: '得，得到的得' },
  'd-i-1': { pinyin: 'dī', hanzi: '水滴 · 低头', sample: '滴，水滴的滴' },
  'd-i-2': { pinyin: 'dí', hanzi: '笛子 · 敌人', sample: '笛，笛子的笛' },
  'd-i-3': { pinyin: 'dǐ', hanzi: '底下 · 底部', sample: '底，底下的底' },
  'd-i-4': { pinyin: 'dì', hanzi: '弟弟 · 土地 · 快递', sample: '弟，弟弟的弟' },
  'd-u-1': { pinyin: 'dū', hanzi: '首都 · 都市', sample: '都，首都的都' },
  'd-u-2': { pinyin: 'dú', hanzi: '读书 · 独自', sample: '读，读书的读' },
  'd-u-3': { pinyin: 'dǔ', hanzi: '堵车 · 睹物', sample: '堵，堵车的堵' },
  'd-u-4': { pinyin: 'dù', hanzi: '肚子 · 温度', sample: '肚，肚子的肚' },
  'd-ai-1': { pinyin: 'dāi', hanzi: '发呆 · 呆呆的', sample: '呆' },
  'd-ai-3': { pinyin: 'dǎi', hanzi: '抓歹徒', sample: '歹' },
  'd-ai-4': { pinyin: 'dài', hanzi: '戴帽子 · 带领 · 带来', sample: '带，带来的带' },
  'd-ui-1': { pinyin: 'duī', hanzi: '堆雪人 · 堆放', sample: '堆，堆雪人的堆' },
  'd-ui-4': { pinyin: 'duì', hanzi: '对不起 · 正确 · 队礼', sample: '对，对不起的对' },
  'd-ao-1': { pinyin: 'dāo', hanzi: '小刀 · 剪刀', sample: '刀，小刀的刀' },
  'd-ao-3': { pinyin: 'dǎo', hanzi: '海岛 · 摔倒', sample: '岛，海岛的岛' },
  'd-ao-4': { pinyin: 'dào', hanzi: '到达 · 道路 · 道德', sample: '到，到达的到' },
  'd-ou-1': { pinyin: 'dōu', hanzi: '都有 · 兜里', sample: '都，都有的都' },
  'd-ou-3': { pinyin: 'dǒu', hanzi: '发抖 · 北斗星', sample: '抖，发抖的抖' },
  'd-ou-4': { pinyin: 'dòu', hanzi: '豆豆 · 逗笑 · 豆腐', sample: '豆，豆豆的豆' },
  'd-iu-1': { pinyin: 'diū', hanzi: '丢掉 · 丢失', sample: '丢，丢掉的丢' },
  'd-ie-1': { pinyin: 'diē', hanzi: '跌倒 · 爹爹', sample: '爹' },
  'd-ie-2': { pinyin: 'dié', hanzi: '蝴蝶 · 飞碟', sample: '蝶，蝴蝶的蝶' },
  'd-an-1': { pinyin: 'dān', hanzi: '单车 · 单纯', sample: '单，单车的单' },
  'd-an-3': { pinyin: 'dǎn', hanzi: '勇敢胆大 · 胆小', sample: '胆，胆小的胆' },
  'd-an-4': { pinyin: 'dàn', hanzi: '鸡蛋 · 蛋糕', sample: '蛋，鸡蛋的蛋' },
  'd-ang-1': { pinyin: 'dāng', hanzi: '当然 · 当作', sample: '当，当然的当' },
  'd-ang-3': { pinyin: 'dǎng', hanzi: '挡雨 · 遮挡', sample: '挡' },
  'd-ang-4': { pinyin: 'dàng', hanzi: '荡秋千 · 荡漾', sample: '荡，荡秋千的荡' },
  'd-eng-1': { pinyin: 'dēng', hanzi: '台灯 · 电灯', sample: '灯，台灯的灯' },
  'd-eng-3': { pinyin: 'děng', hanzi: '等待 · 等等', sample: '等，等待的等' },
  'd-eng-4': { pinyin: 'dèng', hanzi: '板凳 · 蹬腿', sample: '凳，板凳的凳' },
  'd-ing-1': { pinyin: 'dīng', hanzi: '图钉 · 园丁', sample: '钉，图钉的钉' },
  'd-ing-3': { pinyin: 'dǐng', hanzi: '头顶 · 山顶', sample: '顶，头顶的顶' },
  'd-ing-4': { pinyin: 'dìng', hanzi: '一定 · 约定 · 订正', sample: '定，一定的定' },
  'd-ong-1': { pinyin: 'dōng', hanzi: '冬天 · 东方', sample: '东，东方的东' },
  'd-ong-3': { pinyin: 'dǒng', hanzi: '懂事 · 懂得', sample: '懂，懂事的懂' },
  'd-ong-4': { pinyin: 'dòng', hanzi: '运动 · 动物 · 山洞', sample: '动，动物的动' },

  // t
  't-a-1': { pinyin: 'tā', hanzi: '他们 · 她 · 宝塔', sample: '他，他们的他' },
  't-a-3': { pinyin: 'tǎ', hanzi: '宝塔 · 金字塔', sample: '塔，金字塔的塔' },
  't-a-4': { pinyin: 'tà', hanzi: '踏步 · 踏青', sample: '踏，踏步的踏' },
  't-e-4': { pinyin: 'tè', hanzi: '特别 · 特点', sample: '特，特别的特' },
  't-i-1': { pinyin: 'tī', hanzi: '踢球 · 梯子', sample: '踢，踢球的踢' },
  't-i-2': { pinyin: 'tí', hanzi: '提问 · 题目 · 马蹄', sample: '提，提问的提' },
  't-i-3': { pinyin: 'tǐ', hanzi: '体育 · 身体', sample: '体，身体的体' },
  't-i-4': { pinyin: 'tì', hanzi: '代替 · 剃头', sample: '替，代替的替' },
  't-u-1': { pinyin: 'tū', hanzi: '突然 · 突出', sample: '突，突然的突' },
  't-u-2': { pinyin: 'tú', hanzi: '画图 · 涂颜色', sample: '图，画图的图' },
  't-u-3': { pinyin: 'tǔ', hanzi: '泥土 · 土地', sample: '土，泥土的土' },
  't-u-4': { pinyin: 'tù', hanzi: '兔子 · 小白兔', sample: '兔，小兔子的兔' },
  't-ai-1': { pinyin: 'tāi', hanzi: '轮胎 · 双胞胎', sample: '胎' },
  't-ai-2': { pinyin: 'tái', hanzi: '阳台 · 抬头', sample: '台，阳台的台' },
  't-ai-4': { pinyin: 'tài', hanzi: '太阳 · 太棒了', sample: '太，太阳的太' },
  't-ui-1': { pinyin: 'tuī', hanzi: '推门 · 推车', sample: '推，推开的推' },
  't-ui-3': { pinyin: 'tuǐ', hanzi: '小腿 · 大腿', sample: '腿，小腿的腿' },
  't-ui-4': { pinyin: 'tuì', hanzi: '后退 · 退出', sample: '退，后退的退' },
  't-ao-1': { pinyin: 'tāo', hanzi: '掏出来 · 波涛', sample: '掏' },
  't-ao-2': { pinyin: 'táo', hanzi: '桃子 · 逃跑', sample: '桃，桃子的桃' },
  't-ao-3': { pinyin: 'tǎo', hanzi: '讨人喜欢 · 讨厌', sample: '讨' },
  't-ao-4': { pinyin: 'tào', hanzi: '手套 · 一套书', sample: '套，手套的套' },
  't-ou-1': { pinyin: 'tōu', hanzi: '小偷 · 偷偷地', sample: '偷' },
  't-ou-2': { pinyin: 'tóu', hanzi: '头发 · 头部 · 头顶', sample: '头，头发的头' },
  't-ou-4': { pinyin: 'tòu', hanzi: '透明 · 穿透', sample: '透，透明的透' },
  't-ie-1': { pinyin: 'tiē', hanzi: '贴纸 · 贴心', sample: '贴，贴纸的贴' },
  't-ie-3': { pinyin: 'tiě', hanzi: '铁块 · 地铁', sample: '铁，地铁的铁' },
  't-an-1': { pinyin: 'tān', hanzi: '沙滩 · 海滩', sample: '滩，沙滩的滩' },
  't-an-2': { pinyin: 'tán', hanzi: '弹琴 · 谈话', sample: '弹，弹琴的弹' },
  't-an-3': { pinyin: 'tǎn', hanzi: '毛毯 · 平坦', sample: '毯，毛毯的毯' },
  't-an-4': { pinyin: 'tàn', hanzi: '探索 · 叹气', sample: '探，探索的探' },
  't-ang-1': { pinyin: 'tāng', hanzi: '喝汤 · 鸡汤', sample: '汤，喝汤的汤' },
  't-ang-2': { pinyin: 'táng', hanzi: '糖果 · 唐诗 · 池塘', sample: '糖，糖果的糖' },
  't-ang-3': { pinyin: 'tǎng', hanzi: '躺下 · 躺在草地', sample: '躺，躺下的躺' },
  't-ang-4': { pinyin: 'tàng', hanzi: '烫手 · 滚烫', sample: '烫' },
  't-eng-2': { pinyin: 'téng', hanzi: '心疼 · 飞腾 · 树藤', sample: '疼，心疼的疼' },
  't-ing-1': { pinyin: 'tīng', hanzi: '听音乐 · 听话', sample: '听，听话的听' },
  't-ing-2': { pinyin: 'tíng', hanzi: '停止 · 凉亭 · 停留', sample: '停，停止的停' },
  't-ing-3': { pinyin: 'tǐng', hanzi: '挺拔 · 挺好', sample: '挺' },
  't-ong-1': { pinyin: 'tōng', hanzi: '通过 · 通畅', sample: '通，通过的通' },
  't-ong-2': { pinyin: 'tóng', hanzi: '同学 · 童年 · 儿童', sample: '童，童年的童' },
  't-ong-3': { pinyin: 'tǒng', hanzi: '水桶 · 垃圾桶', sample: '桶，水桶的桶' },
  't-ong-4': { pinyin: 'tòng', hanzi: '疼痛 · 痛苦', sample: '痛，疼痛的痛' },

  // n
  'n-a-2': { pinyin: 'ná', hanzi: '拿东西 · 拿到', sample: '拿，拿书的拿' },
  'n-a-3': { pinyin: 'nǎ', hanzi: '哪里 · 哪个', sample: '哪，哪里的哪' },
  'n-a-4': { pinyin: 'nà', hanzi: '那个 · 那里', sample: '那，那个的那' },
  'n-e-2': { pinyin: 'né', hanzi: '哪吒闹海', sample: '吒，哪吒的哪' },
  'n-i-2': { pinyin: 'ní', hanzi: '泥土 · 泥巴', sample: '泥，泥土的泥' },
  'n-i-3': { pinyin: 'nǐ', hanzi: '你好 · 你们', sample: '你，你好的你' },
  'n-i-4': { pinyin: 'nì', hanzi: '油腻 · 逆风', sample: '腻' },
  'n-u-2': { pinyin: 'nú', hanzi: '奴隶', sample: '奴' },
  'n-u-3': { pinyin: 'nǔ', hanzi: '努力 · 努把力', sample: '努，努力的努' },
  'n-u-4': { pinyin: 'nù', hanzi: '发怒 · 愤怒', sample: '怒，发怒的怒' },
  'n-ü-3': { pinyin: 'nǚ', hanzi: '女生 · 女孩 · 女儿', sample: '女，女孩的女' },
  'n-ai-3': { pinyin: 'nǎi', hanzi: '奶奶 · 牛奶', sample: '奶，牛奶的奶' },
  'n-ai-4': { pinyin: 'nài', hanzi: '耐心 · 耐力', sample: '耐，耐心的耐' },
  'n-ei-4': { pinyin: 'nèi', hanzi: '内容 · 室内', sample: '内，内容的内' },
  'n-ao-2': { pinyin: 'náo', hanzi: '抓挠', sample: '挠' },
  'n-ao-3': { pinyin: 'nǎo', hanzi: '脑筋 · 烦恼', sample: '脑，电脑的脑' },
  'n-ao-4': { pinyin: 'nào', hanzi: '热闹 · 闹钟', sample: '闹，闹钟的闹' },
  'n-iu-1': { pinyin: 'niū', hanzi: '小妞妞', sample: '妞' },
  'n-iu-2': { pinyin: 'niú', hanzi: '小牛 · 黄牛 · 牛奶', sample: '牛，小牛的牛' },
  'n-iu-3': { pinyin: 'niǔ', hanzi: '纽扣 · 扭动', sample: '纽，纽扣的纽' },
  'n-ie-1': { pinyin: 'niē', hanzi: '捏泥人 · 捏住', sample: '捏，捏泥人的捏' },
  'n-ie-4': { pinyin: 'niè', hanzi: '姓聂', sample: '聂' },
  'n-üe-4': { pinyin: 'nüè', hanzi: '疟疾', sample: '疟' },
  'n-an-2': { pinyin: 'nán', hanzi: '南方 · 男孩 · 困难', sample: '南，南方的南' },
  'n-an-4': { pinyin: 'nàn', hanzi: '苦难', sample: '难' },
  'n-en-4': { pinyin: 'nèn', hanzi: '嫩绿 · 嫩叶', sample: '嫩，嫩绿的嫩' },
  'n-in-2': { pinyin: 'nín', hanzi: '您好 · 敬称您', sample: '您，您好的您' },
  'n-ang-2': { pinyin: 'náng', hanzi: '口袋 · 囊中', sample: '囊' },
  'n-eng-2': { pinyin: 'néng', hanzi: '能够 · 能量 · 能力', sample: '能，能力的能' },
  'n-ing-2': { pinyin: 'níng', hanzi: '柠檬 · 安宁', sample: '柠，柠檬的柠' },
  'n-ing-4': { pinyin: 'nìng', hanzi: '宁静 · 宁可', sample: '宁，宁静的宁' },
  'n-ong-2': { pinyin: 'nóng', hanzi: '农民 · 浓厚', sample: '农，农民的农' },
  'n-ong-4': { pinyin: 'nòng', hanzi: '玩弄 · 弄懂', sample: '弄' },

  // l
  'l-a-1': { pinyin: 'lā', hanzi: '拉手 · 垃圾', sample: '拉，拉小手的拉' },
  'l-a-3': { pinyin: 'lǎ', hanzi: '喇叭 · 大喇叭', sample: '喇，大喇叭的喇' },
  'l-a-4': { pinyin: 'là', hanzi: '辣椒 · 辛辣', sample: '辣，辣椒的辣' },
  'l-e-4': { pinyin: 'lè', hanzi: '快乐 · 乐曲', sample: '乐，快乐的乐' },
  'l-i-2': { pinyin: 'lí', hanzi: '梨子 · 离开', sample: '梨，梨子的梨' },
  'l-i-3': { pinyin: 'lǐ', hanzi: '礼物 · 里面 · 礼貌', sample: '礼，礼物的礼' },
  'l-i-4': { pinyin: 'lì', hanzi: '美丽 · 力气 · 鼓励', sample: '力，力气的力' },
  'l-u-2': { pinyin: 'lú', hanzi: '芦苇 · 炉子', sample: '芦' },
  'l-u-3': { pinyin: 'lǔ', hanzi: '鲁班 · 粗鲁', sample: '鲁' },
  'l-u-4': { pinyin: 'lù', hanzi: '马路 · 长颈鹿 · 露水', sample: '路，马路的路' },
  'l-ü-2': { pinyin: 'lǘ', hanzi: '小毛驴', sample: '驴，小毛驴的驴' },
  'l-ü-3': { pinyin: 'lǚ', hanzi: '旅行 · 屡次', sample: '旅，旅行的旅' },
  'l-ü-4': { pinyin: 'lǜ', hanzi: '绿色 · 规律', sample: '绿，绿色的绿' },
  'l-ai-2': { pinyin: 'lái', hanzi: '来到 · 过来', sample: '来，过来的来' },
  'l-ei-2': { pinyin: 'léi', hanzi: '打雷 · 雷雨', sample: '雷，打雷的雷' },
  'l-ei-3': { pinyin: 'lěi', hanzi: '累积 · 堡垒', sample: '垒' },
  'l-ei-4': { pinyin: 'lèi', hanzi: '眼泪 · 劳累 · 类别', sample: '泪，眼泪的泪' },
  'l-ao-1': { pinyin: 'lāo', hanzi: '捞起 · 捕捞', sample: '捞' },
  'l-ao-2': { pinyin: 'láo', hanzi: '劳动 · 牢记', sample: '劳，劳动的劳' },
  'l-ao-3': { pinyin: 'lǎo', hanzi: '老师 · 老虎 · 老人', sample: '老，老师的老' },
  'l-ao-4': { pinyin: 'lào', hanzi: '烙饼', sample: '烙' },
  'l-ou-2': { pinyin: 'lóu', hanzi: '高楼 · 大楼', sample: '楼，大楼的楼' },
  'l-ou-3': { pinyin: 'lǒu', hanzi: '搂抱', sample: '搂' },
  'l-ou-4': { pinyin: 'lòu', hanzi: '露水 · 漏雨', sample: '露，露水的露' },
  'l-iu-1': { pinyin: 'liū', hanzi: '溜冰 · 溜溜球', sample: '溜，溜冰的溜' },
  'l-iu-2': { pinyin: 'liú', hanzi: '流水 · 柳树', sample: '流，流水的流' },
  'l-iu-3': { pinyin: 'liǔ', hanzi: '柳树 · 柳叶', sample: '柳，柳树的柳' },
  'l-iu-4': { pinyin: 'liù', hanzi: '数字六 · 六角形', sample: '六，数字六的六' },
  'l-ie-4': { pinyin: 'liè', hanzi: '排列 · 列车 · 强烈', sample: '列，列车的列' },
  'l-üe-4': { pinyin: 'lüè', hanzi: '省略 · 策略', sample: '略，省略的略' },
  'l-an-2': { pinyin: 'lán', hanzi: '蓝色 · 蓝天 · 摇篮', sample: '蓝，蓝天的蓝' },
  'l-an-3': { pinyin: 'lǎn', hanzi: '懒惰 · 懒洋洋', sample: '懒' },
  'l-an-4': { pinyin: 'làn', hanzi: '灿烂 · 破烂', sample: '烂，灿烂的烂' },
  'l-in-2': { pinyin: 'lín', hanzi: '森林 · 树林 · 邻居', sample: '林，森林的林' },
  'l-in-3': { pinyin: 'lǐn', hanzi: '凛冽', sample: '凛' },
  'l-ang-2': { pinyin: 'láng', hanzi: '大灰狼 · 走廊', sample: '狼，大灰狼的狼' },
  'l-ang-3': { pinyin: 'lǎng', hanzi: '晴朗 · 开朗', sample: '朗，晴朗的朗' },
  'l-ang-4': { pinyin: 'làng', hanzi: '波浪 · 浪花', sample: '浪，浪花的浪' },
  'l-eng-3': { pinyin: 'lěng', hanzi: '寒冷 · 冷水', sample: '冷，寒冷的冷' },
  'l-eng-4': { pinyin: 'lèng', hanzi: '发愣', sample: '愣' },
  'l-ing-2': { pinyin: 'líng', hanzi: '铃铛 · 机灵 · 零食', sample: '铃，铃铛的铃' },
  'l-ing-3': { pinyin: 'lǐng', hanzi: '红领巾 · 带领', sample: '领，红领巾的领' },
  'l-ing-4': { pinyin: 'lìng', hanzi: '命令 · 另外', sample: '令，命令的令' },
  'l-ong-2': { pinyin: 'lóng', hanzi: '巨龙 · 鸟笼', sample: '龙，巨龙的龙' },
  'l-ong-3': { pinyin: 'lǒng', hanzi: '笼罩', sample: '笼' },

  // g
  'g-a-1': { pinyin: 'gā', hanzi: '鸭子嘎嘎叫 · 咖喱', sample: '嘎，嘎嘎叫的嘎' },
  'g-e-1': { pinyin: 'gē', hanzi: '哥哥 · 唱歌 · 鸽子', sample: '哥，哥哥的哥' },
  'g-e-2': { pinyin: 'gé', hanzi: '格子 · 四线三格', sample: '格，四线三格的格' },
  'g-e-4': { pinyin: 'gè', hanzi: '各个 · 个人 · 个子', sample: '个，一个两个的个' },
  'g-u-1': { pinyin: 'gū', hanzi: '姑姑 · 姑娘', sample: '姑，姑姑的姑' },
  'g-u-3': { pinyin: 'gǔ', hanzi: '打鼓 · 骨头 · 古老', sample: '鼓，打鼓的鼓' },
  'g-u-4': { pinyin: 'gù', hanzi: '故事 · 故乡', sample: '故，故事的故' },
  'g-ai-1': { pinyin: 'gāi', hanzi: '应该 · 该做', sample: '该，应该的该' },
  'g-ai-3': { pinyin: 'gǎi', hanzi: '改正 · 改错', sample: '改，改正的改' },
  'g-ai-4': { pinyin: 'gài', hanzi: '盖子 · 盖房子', sample: '盖，盖子的盖' },
  'g-ei-3': { pinyin: 'gěi', hanzi: '送给 · 给你', sample: '给，送给的给' },
  'g-ui-1': { pinyin: 'guī', hanzi: '乌龟 · 规则', sample: '龟，乌龟的龟' },
  'g-ui-3': { pinyin: 'guǐ', hanzi: '轨道 · 魔鬼', sample: '轨，轨道的轨' },
  'g-ui-4': { pinyin: 'guì', hanzi: '桂花 · 昂贵', sample: '桂，桂花的桂' },
  'g-ao-1': { pinyin: 'gāo', hanzi: '高大 · 蛋糕 · 高兴', sample: '高，高大的高' },
  'g-ao-3': { pinyin: 'gǎo', hanzi: '稿件 · 搞笑', sample: '搞' },
  'g-ao-4': { pinyin: 'gào', hanzi: '告诉 · 报告', sample: '告，告诉的告' },
  'g-ou-1': { pinyin: 'gōu', hanzi: '钩子 · 水沟', sample: '钩' },
  'g-ou-3': { pinyin: 'gǒu', hanzi: '小狗 · 花狗', sample: '狗，小狗的狗' },
  'g-ou-4': { pinyin: 'gòu', hanzi: '足够 · 购买', sample: '够，足够的够' },
  'g-an-1': { pinyin: 'gān', hanzi: '干净 · 饼干', sample: '干，干净的干' },
  'g-an-3': { pinyin: 'gǎn', hanzi: '勇敢 · 感动 · 赶快', sample: '敢，勇敢的敢' },
  'g-an-4': { pinyin: 'gàn', hanzi: '干活 · 树干', sample: '干' },
  'g-en-1': { pinyin: 'gēn', hanzi: '树根 · 跟着', sample: '根，树根的根' },
  'g-ang-1': { pinyin: 'gāng', hanzi: '刚才 · 水缸 · 钢笔', sample: '刚，刚才的刚' },
  'g-ang-3': { pinyin: 'gǎng', hanzi: '港口 · 香港', sample: '港，港口的港' },
  'g-ang-4': { pinyin: 'gàng', hanzi: '单杠 · 双杠', sample: '杠' },
  'g-eng-1': { pinyin: 'gēng', hanzi: '更换 · 耕田', sample: '耕' },
  'g-eng-3': { pinyin: 'gěng', hanzi: '花梗', sample: '梗' },
  'g-eng-4': { pinyin: 'gèng', hanzi: '更加 · 更好', sample: '更，更加的更' },
  'g-ong-1': { pinyin: 'gōng', hanzi: '工人 · 公园 · 工作', sample: '工，工人的工' },
  'g-ong-3': { pinyin: 'gǒng', hanzi: '拱桥 · 拱门', sample: '拱，拱桥的拱' },
  'g-ong-4': { pinyin: 'gòng', hanzi: '一共 · 共同', sample: '共，一共的共' },

  // k
  'k-a-1': { pinyin: 'kā', hanzi: '咖啡 · 咔嚓', sample: '咖，咖啡的咖' },
  'k-a-3': { pinyin: 'kǎ', hanzi: '卡片 · 贺卡 · 卡车', sample: '卡，卡片的卡' },
  'k-e-1': { pinyin: 'kē', hanzi: '科学 · 一颗星 · 棵树', sample: '科，科学的科' },
  'k-e-2': { pinyin: 'ké', hanzi: '贝壳 · 咳嗽', sample: '壳，贝壳的壳' },
  'k-e-3': { pinyin: 'kě', hanzi: '可以 · 口渴 · 可爱', sample: '可，可以的可' },
  'k-e-4': { pinyin: 'kè', hanzi: '上课 · 客人 · 刻苦', sample: '课，上课的课' },
  'k-u-1': { pinyin: 'kū', hanzi: '哭泣 · 哭脸', sample: '哭，哭泣的哭' },
  'k-u-3': { pinyin: 'kǔ', hanzi: '辛苦 · 苦瓜', sample: '苦，辛苦的苦' },
  'k-u-4': { pinyin: 'kù', hanzi: '裤子 · 酷酷的', sample: '裤，裤子的裤' },
  'k-ai-1': { pinyin: 'kāi', hanzi: '开门 · 开心 · 开学', sample: '开，开心的开' },
  'k-ai-3': { pinyin: 'kǎi', hanzi: '凯旋 · 铠甲', sample: '凯' },
  'k-ui-1': { pinyin: 'kuī', hanzi: '吃亏', sample: '亏' },
  'k-ui-2': { pinyin: 'kuí', hanzi: '向日葵', sample: '葵，向日葵的葵' },
  'k-ui-4': { pinyin: 'kuì', hanzi: '惭愧', sample: '愧' },
  'k-ao-3': { pinyin: 'kǎo', hanzi: '考试 · 思考 · 烤鸭', sample: '考，考试的考' },
  'k-ao-4': { pinyin: 'kào', hanzi: '靠近 · 依靠', sample: '靠，依靠的靠' },
  'k-ou-3': { pinyin: 'kǒu', hanzi: '口水 · 门口 · 口袋', sample: '口，门口的口' },
  'k-ou-4': { pinyin: 'kòu', hanzi: '纽扣 · 扣上', sample: '扣，纽扣的扣' },
  'k-an-1': { pinyin: 'kān', hanzi: '看守 · 刊登', sample: '刊' },
  'k-an-3': { pinyin: 'kǎn', hanzi: '砍树', sample: '砍' },
  'k-an-4': { pinyin: 'kàn', hanzi: '看见 · 看书 · 看望', sample: '看，看书的看' },
  'k-en-3': { pinyin: 'kěn', hanzi: '肯定 · 肯德基', sample: '肯，肯定的肯' },
  'k-ang-1': { pinyin: 'kāng', hanzi: '健康 · 康乃馨', sample: '康，健康的康' },
  'k-ang-4': { pinyin: 'kàng', hanzi: '抵抗 · 炕', sample: '抗' },
  'k-eng-1': { pinyin: 'kēng', hanzi: '水坑 · 坑洼', sample: '坑' },
  'k-ong-1': { pinyin: 'kōng', hanzi: '天空 · 空气 · 空手', sample: '空，天空的空' },
  'k-ong-3': { pinyin: 'kǒng', hanzi: '孔雀 · 害怕', sample: '孔，孔雀的孔' },
  'k-ong-4': { pinyin: 'kòng', hanzi: '有空 · 控制', sample: '控' },

  // h
  'h-a-1': { pinyin: 'hā', hanzi: '哈哈大笑 · 哈密瓜', sample: '哈，哈密瓜的哈' },
  'h-a-2': { pinyin: 'há', hanzi: '蛤蟆', sample: '蛤' },
  'h-e-1': { pinyin: 'hē', hanzi: '喝水 · 喝汤', sample: '喝，喝水的喝' },
  'h-e-2': { pinyin: 'hé', hanzi: '荷花 · 河流 · 和平', sample: '河，河流的河' },
  'h-e-4': { pinyin: 'hè', hanzi: '祝贺 · 白鹤 · 喝彩', sample: '贺，祝贺的贺' },
  'h-u-1': { pinyin: 'hū', hanzi: '呼吸 · 呼唤', sample: '呼，呼吸的呼' },
  'h-u-2': { pinyin: 'hú', hanzi: '狐狸 · 蝴蝶 · 湖泊', sample: '狐，狐狸的狐' },
  'h-u-3': { pinyin: 'hǔ', hanzi: '老虎 · 猛虎', sample: '虎，老虎的虎' },
  'h-u-4': { pinyin: 'hù', hanzi: '保护 · 互相 · 护士', sample: '护，保护的护' },
  'h-ai-1': { pinyin: 'hāi', hanzi: '嗨 · 嗨皮', sample: '嗨' },
  'h-ai-2': { pinyin: 'hái', hanzi: '孩子 · 小孩 · 还有', sample: '孩，小孩子的孩' },
  'h-ai-3': { pinyin: 'hǎi', hanzi: '大海 · 海浪 · 海洋', sample: '海，大海的海' },
  'h-ai-4': { pinyin: 'hài', hanzi: '害怕 · 害羞 · 伤害', sample: '害，害怕的害' },
  'h-ei-1': { pinyin: 'hēi', hanzi: '黑色 · 黑夜 · 黑板', sample: '黑，黑色的黑' },
  'h-ui-1': { pinyin: 'huī', hanzi: '灰色 · 挥手 · 光辉', sample: '灰，灰色的灰' },
  'h-ui-2': { pinyin: 'huí', hanzi: '回家 · 回答', sample: '回，回家的回' },
  'h-ui-3': { pinyin: 'huǐ', hanzi: '后悔 · 悔改', sample: '悔' },
  'h-ui-4': { pinyin: 'huì', hanzi: '学会 · 开会 · 绘画', sample: '会，学会的会' },
  'h-ao-2': { pinyin: 'háo', hanzi: '自豪 · 豪杰', sample: '豪，自豪的豪' },
  'h-ao-3': { pinyin: 'hǎo', hanzi: '好朋友 · 好的 · 好看', sample: '好，好朋友的好' },
  'h-ao-4': { pinyin: 'hào', hanzi: '问号 · 学号 · 爱好', sample: '号，问号的号' },
  'h-ou-2': { pinyin: 'hóu', hanzi: '小猴子 · 金丝猴', sample: '猴，小猴子的猴' },
  'h-ou-3': { pinyin: 'hǒu', hanzi: '大吼 · 吼叫', sample: '吼' },
  'h-ou-4': { pinyin: 'hòu', hanzi: '后面 · 时候 · 厚厚', sample: '后，后面的后' },
  'h-an-1': { pinyin: 'hān', hanzi: '憨厚 · 憨豆', sample: '憨' },
  'h-an-2': { pinyin: 'hán', hanzi: '寒冷 · 冬寒', sample: '寒，寒冷的寒' },
  'h-an-3': { pinyin: 'hǎn', hanzi: '喊叫 · 大喊', sample: '喊，喊叫的喊' },
  'h-an-4': { pinyin: 'hàn', hanzi: '流汗 · 汗水 · 汉字', sample: '汉，汉字的汉' },
  'h-en-2': { pinyin: 'hén', hanzi: '痕迹', sample: '痕' },
  'h-en-3': { pinyin: 'hěn', hanzi: '很好 · 很多', sample: '很，很好的很' },
  'h-en-4': { pinyin: 'hèn', hanzi: '仇恨', sample: '恨' },
  'h-ang-2': { pinyin: 'háng', hanzi: '行业 · 银行', sample: '行，银行的行' },
  'h-eng-1': { pinyin: 'hēng', hanzi: '哼歌 · 哼一声', sample: '哼' },
  'h-eng-2': { pinyin: 'héng', hanzi: '横线 · 平衡', sample: '横，横线的横' },
  'h-ong-1': { pinyin: 'hōng', hanzi: '轰隆隆 · 轰动', sample: '轰，轰隆隆的轰' },
  'h-ong-2': { pinyin: 'hóng', hanzi: '红色 · 彩虹 · 红旗', sample: '红，红色的红' },
  'h-ong-3': { pinyin: 'hǒng', hanzi: '哄宝宝睡觉', sample: '哄' },

  // j
  'j-i-1': { pinyin: 'jī', hanzi: '小鸡 · 飞机 · 机会', sample: '鸡，小鸡的鸡' },
  'j-i-2': { pinyin: 'jí', hanzi: '吉利 · 集合 · 着急', sample: '吉，吉利的吉' },
  'j-i-3': { pinyin: 'jǐ', hanzi: '自己 · 几个 · 拥挤', sample: '己，自己的己' },
  'j-i-4': { pinyin: 'jì', hanzi: '记住 · 季节 · 寄信', sample: '记，记住的记' },
  'j-ü-1': { pinyin: 'jū', hanzi: '居住 · 鞠躬 (小ü脱帽成ju)', sample: '居，居住的居' },
  'j-ü-2': { pinyin: 'jú', hanzi: '橘子 · 菊花', sample: '橘，橘子的橘' },
  'j-ü-3': { pinyin: 'jǔ', hanzi: '举手 · 举起', sample: '举，举手的举' },
  'j-ü-4': { pinyin: 'jù', hanzi: '巨大 · 句号 · 距离', sample: '巨，巨大的巨' },
  'j-iu-1': { pinyin: 'jiū', hanzi: '揪住', sample: '揪' },
  'j-iu-3': { pinyin: 'jiǔ', hanzi: '数字九 · 永久', sample: '九，数字九的九' },
  'j-iu-4': { pinyin: 'jiù', hanzi: '救人 · 旧书 · 舅舅', sample: '救，救人的救' },
  'j-ie-1': { pinyin: 'jiē', hanzi: '街道 · 接着 · 迎接', sample: '街，街道的街' },
  'j-ie-2': { pinyin: 'jié', hanzi: '节日 · 洁白 · 结实', sample: '节，节日的节' },
  'j-ie-3': { pinyin: 'jiě', hanzi: '姐姐 · 解答', sample: '姐，姐姐的姐' },
  'j-ie-4': { pinyin: 'jiè', hanzi: '借书 · 介绍 · 世界', sample: '借，借书的借' },
  'j-üe-1': { pinyin: 'juē', hanzi: '撅嘴', sample: '撅' },
  'j-üe-2': { pinyin: 'jué', hanzi: '觉得 · 决定 · 绝妙', sample: '觉，觉得的觉' },
  'j-an-3': { pinyin: 'jiǎn', hanzi: '剪刀 · 减法 · 捡起', sample: '剪，剪刀的剪' },
  'j-an-4': { pinyin: 'jiàn', hanzi: '看见 · 件数 · 建造', sample: '见，看见的见' },
  'j-in-1': { pinyin: 'jīn', hanzi: '金子 · 今天 · 斤两', sample: '金，金子的金' },
  'j-in-3': { pinyin: 'jǐn', hanzi: '抓紧 · 尽管', sample: '紧，抓紧的紧' },
  'j-in-4': { pinyin: 'jìn', hanzi: '前进 · 远近 · 进入', sample: '进，前进的进' },
  'j-ing-1': { pinyin: 'jīng', hanzi: '眼睛 · 北京 · 京剧', sample: '睛，眼睛的睛' },
  'j-ing-3': { pinyin: 'jǐng', hanzi: '风景 · 水井 · 警察', sample: '景，风景的景' },
  'j-ing-4': { pinyin: 'jìng', hanzi: '安静 · 干净 · 敬礼', sample: '静，安静的静' },

  // q
  'q-i-1': { pinyin: 'qī', hanzi: '数字七 · 期末 · 漆黑', sample: '七，数字七的七' },
  'q-i-2': { pinyin: 'qí', hanzi: '骑马 · 国旗 · 奇妙', sample: '旗，国旗的旗' },
  'q-i-3': { pinyin: 'qǐ', hanzi: '起来 · 起床 · 启发', sample: '起，起来的起' },
  'q-i-4': { pinyin: 'qì', hanzi: '空气 · 汽车 · 生气', sample: '气，空气的气' },
  'q-ü-1': { pinyin: 'qū', hanzi: '弯曲 · 区分 (小ü脱帽成qu)', sample: '曲，弯曲的曲' },
  'q-ü-2': { pinyin: 'qú', hanzi: '水渠 · 渠道', sample: '渠，水渠的渠' },
  'q-ü-3': { pinyin: 'qǔ', hanzi: '取得 · 歌曲', sample: '取，取得的取' },
  'q-ü-4': { pinyin: 'qù', hanzi: '回去 · 有趣 · 去年', sample: '去，回去的去' },
  'q-iu-1': { pinyin: 'qiū', hanzi: '秋天 · 蚯蚓', sample: '秋，秋天的秋' },
  'q-iu-2': { pinyin: 'qiú', hanzi: '皮球 · 足球 · 地球', sample: '球，皮球的球' },
  'q-ie-1': { pinyin: 'qiē', hanzi: '切西瓜 · 刀切', sample: '切，切西瓜的切' },
  'q-ie-2': { pinyin: 'qié', hanzi: '茄子 · 紫茄', sample: '茄，茄子的茄' },
  'q-ie-3': { pinyin: 'qiě', hanzi: '而且 · 并且', sample: '且' },
  'q-ie-4': { pinyin: 'qiè', hanzi: '亲切 · 一切', sample: '切，亲切的切' },
  'q-üe-1': { pinyin: 'quē', hanzi: '缺少 · 缺点', sample: '缺，缺少的缺' },
  'q-üe-4': { pinyin: 'què', hanzi: '喜鹊 · 正确', sample: '鹊，喜鹊的鹊' },
  'q-in-1': { pinyin: 'qīn', hanzi: '亲人 · 亲吻 · 亲切', sample: '亲，亲人的亲' },
  'q-in-2': { pinyin: 'qín', hanzi: '勤劳 · 钢琴', sample: '勤，勤劳的勤' },
  'q-ing-1': { pinyin: 'qīng', hanzi: '蜻蜓 · 青草 · 轻重', sample: '青，青草的青' },
  'q-ing-2': { pinyin: 'qíng', hanzi: '晴天 · 事情 · 心情', sample: '晴，晴天的晴' },
  'q-ing-3': { pinyin: 'qǐng', hanzi: '请坐 · 请客 · 请教', sample: '请，请客的请' },
  'q-ing-4': { pinyin: 'qìng', hanzi: '庆祝 · 庆贺', sample: '庆，庆祝的庆' },

  // x
  'x-i-1': { pinyin: 'xī', hanzi: '西瓜 · 喜欢 · 东方西方', sample: '西，西瓜的西' },
  'x-i-2': { pinyin: 'xí', hanzi: '学习 · 席子', sample: '习，学习的习' },
  'x-i-3': { pinyin: 'xǐ', hanzi: '洗手 · 洗澡 · 喜欢', sample: '洗，洗手的洗' },
  'x-i-4': { pinyin: 'xì', hanzi: '唱戏 · 细心 · 关系', sample: '戏，唱戏的戏' },
  'x-ü-1': { pinyin: 'xū', hanzi: '胡须 · 需要 (小ü脱帽成xu)', sample: '须，胡须的须' },
  'x-ü-2': { pinyin: 'xú', hanzi: '徐徐上升 · 姓徐', sample: '徐，徐徐上升的徐' },
  'x-ü-3': { pinyin: 'xǔ', hanzi: '允许 · 许愿 · 许多', sample: '许，许多的许' },
  'x-ü-4': { pinyin: 'xù', hanzi: '继续 · 情绪 · 顺序', sample: '续，继续的续' },
  'x-iu-1': { pinyin: 'xiū', hanzi: '休息 · 修理', sample: '休，休息的休' },
  'x-iu-4': { pinyin: 'xiù', hanzi: '优秀 · 秀丽', sample: '秀，优秀的秀' },
  'x-ie-1': { pinyin: 'xiē', hanzi: '一些 · 歇息', sample: '些，一些的些' },
  'x-ie-2': { pinyin: 'xié', hanzi: '鞋子 · 斜线 · 和谐', sample: '鞋，鞋子的鞋' },
  'x-ie-3': { pinyin: 'xiě', hanzi: '写字 · 写作', sample: '写，写字的写' },
  'x-ie-4': { pinyin: 'xiè', hanzi: '谢谢 · 感谢 · 树叶凋谢', sample: '谢，谢谢的谢' },
  'x-üe-1': { pinyin: 'xuē', hanzi: '靴子 · 削笔', sample: '靴' },
  'x-üe-2': { pinyin: 'xué', hanzi: '学生 · 学习 · 学校', sample: '学，学习的学' },
  'x-üe-3': { pinyin: 'xuě', hanzi: '雪花 · 下雪 · 白雪', sample: '雪，雪花的雪' },
  'x-in-1': { pinyin: 'xīn', hanzi: '新年 · 爱心 · 新旧', sample: '心，爱心的新' },
  'x-in-4': { pinyin: 'xìn', hanzi: '写信 · 信任 · 相信', sample: '信，相信的信' },
  'x-ing-1': { pinyin: 'xīng', hanzi: '星星 · 星期', sample: '星，星星的星' },
  'x-ing-2': { pinyin: 'xíng', hanzi: '行动 · 行走 · 行星', sample: '行，行动的行' },
  'x-ing-3': { pinyin: 'xǐng', hanzi: '醒来 · 提醒', sample: '醒，醒来的醒' },
  'x-ing-4': { pinyin: 'xìng', hanzi: '高兴 · 姓名 · 幸福', sample: '兴，高兴的兴' },

  // zh
  'zh-a-1': { pinyin: 'zhā', hanzi: '打针扎针 · 扎辫子', sample: '扎' },
  'zh-a-2': { pinyin: 'zhá', hanzi: '油炸薯条', sample: '炸' },
  'zh-a-3': { pinyin: 'zhǎ', hanzi: '眨眼睛', sample: '眨，眨眼的眨' },
  'zh-a-4': { pinyin: 'zhà', hanzi: '爆炸 · 炸弹', sample: '炸，爆炸的炸' },
  'zh-e-1': { pinyin: 'zhē', hanzi: '遮阳伞 · 遮挡', sample: '遮，遮挡的遮' },
  'zh-e-2': { pinyin: 'zhé', hanzi: '折纸 · 折断', sample: '折，折纸的折' },
  'zh-e-3': { pinyin: 'zhě', hanzi: '作者 · 学者', sample: '者' },
  'zh-e-4': { pinyin: 'zhè', hanzi: '这个 · 这里 · 这边', sample: '这，这个的这' },
  'zh-i-1': { pinyin: 'zhī', hanzi: '知道 · 一只小鸟 · 树枝', sample: '知，知道的知' },
  'zh-i-2': { pinyin: 'zhí', hanzi: '植物 · 笔直 · 植树', sample: '植，植物的植' },
  'zh-i-3': { pinyin: 'zhǐ', hanzi: '手指 · 白纸 · 只有', sample: '纸，白纸的纸' },
  'zh-i-4': { pinyin: 'zhì', hanzi: '智慧 · 志向 · 制作', sample: '智，智慧的智' },
  'zh-u-1': { pinyin: 'zhū', hanzi: '小猪 · 珍珠 · 蜘蛛', sample: '猪，小猪的猪' },
  'zh-u-2': { pinyin: 'zhú', hanzi: '竹子 · 竹林', sample: '竹，竹子的竹' },
  'zh-u-3': { pinyin: 'zhǔ', hanzi: '煮饭 · 主人', sample: '主，主人的主' },
  'zh-u-4': { pinyin: 'zhù', hanzi: '注意 · 帮助 · 住院', sample: '助，帮助的助' },
  'zh-ai-1': { pinyin: 'zhāi', hanzi: '摘苹果 · 采摘', sample: '摘，摘苹果的摘' },
  'zh-ai-3': { pinyin: 'zhǎi', hanzi: '狭窄', sample: '窄' },
  'zh-ui-1': { pinyin: 'zhuī', hanzi: '追赶 · 追求', sample: '追，追赶的追' },
  'zh-ui-4': { pinyin: 'zhuì', hanzi: '坠落', sample: '坠' },
  'zh-ao-1': { pinyin: 'zhāo', hanzi: '招手 · 招揽', sample: '招，招手的招' },
  'zh-ao-2': { pinyin: 'zháo', hanzi: '着急 · 着火', sample: '着，着火的着' },
  'zh-ao-3': { pinyin: 'zhǎo', hanzi: '爪子 · 鹰爪', sample: '爪，爪子的爪' },
  'zh-ao-4': { pinyin: 'zhào', hanzi: '照相 · 照顾 · 照射', sample: '照，照相的照' },
  'zh-ou-1': { pinyin: 'zhōu', hanzi: '周围 · 喝粥 · 小舟', sample: '周，周围的周' },
  'zh-ou-3': { pinyin: 'zhǒu', hanzi: '手肘', sample: '肘' },
  'zh-ou-4': { pinyin: 'zhòu', hanzi: '宇宙 · 白昼', sample: '宙，宇宙的宙' },
  'zh-an-1': { pinyin: 'zhān', hanzi: '粘贴 · 粘住', sample: '粘' },
  'zh-an-3': { pinyin: 'zhǎn', hanzi: '展示 · 展开', sample: '展，展开的展' },
  'zh-an-4': { pinyin: 'zhàn', hanzi: '站立 · 车站 · 战斗', sample: '站，车站的站' },
  'zh-en-1': { pinyin: 'zhēn', hanzi: '打针 · 真正 · 珍珠', sample: '真，真正的真' },
  'zh-en-3': { pinyin: 'zhěn', hanzi: '枕头', sample: '枕，枕头的枕' },
  'zh-en-4': { pinyin: 'zhèn', hanzi: '小镇 · 阵雨', sample: '镇，小镇的镇' },
  'zh-ang-1': { pinyin: 'zhāng', hanzi: '张开嘴 · 一张纸', sample: '张，一张纸的张' },
  'zh-ang-3': { pinyin: 'zhǎng', hanzi: '长大 · 手掌 · 掌声', sample: '长，长大的长' },
  'zh-ang-4': { pinyin: 'zhàng', hanzi: '拐杖 · 蚊帐', sample: '杖，拐杖的杖' },
  'zh-eng-1': { pinyin: 'zhēng', hanzi: '争吵 · 睁开眼', sample: '睁，睁开眼的睁' },
  'zh-eng-3': { pinyin: 'zhěng', hanzi: '整理 · 整个', sample: '整，整理的整' },
  'zh-eng-4': { pinyin: 'zhèng', hanzi: '正确 · 正在 · 政治', sample: '正，正确的正' },
  'zh-ong-1': { pinyin: 'zhōng', hanzi: '中国 · 时钟 · 中间', sample: '中，中国的中' },
  'zh-ong-3': { pinyin: 'zhǒng', hanzi: '种子 · 各种', sample: '种，种子的种' },
  'zh-ong-4': { pinyin: 'zhòng', hanzi: '重要 · 植树种花 · 重轻', sample: '重，重要的重' },

  // ch
  'ch-a-1': { pinyin: 'chā', hanzi: '叉子 · 插花', sample: '叉，叉子的叉' },
  'ch-a-2': { pinyin: 'chá', hanzi: '喝茶 · 检查 · 查字典', sample: '茶，喝茶的茶' },
  'ch-a-4': { pinyin: 'chà', hanzi: '差不多 · 差错', sample: '差' },
  'ch-e-1': { pinyin: 'chē', hanzi: '汽车 · 自行车 · 车站', sample: '车，汽车的车' },
  'ch-e-3': { pinyin: 'chě', hanzi: '扯开', sample: '扯' },
  'ch-e-4': { pinyin: 'chè', hanzi: '彻底 · 撤退', sample: '彻' },
  'ch-i-1': { pinyin: 'chī', hanzi: '吃饭 · 吃水果', sample: '吃，吃饭的吃' },
  'ch-i-2': { pinyin: 'chí', hanzi: '池塘 · 迟到 · 奔驰', sample: '池，池塘的池' },
  'ch-i-3': { pinyin: 'chǐ', hanzi: '尺子 · 牙齿', sample: '尺，尺子的尺' },
  'ch-i-4': { pinyin: 'chì', hanzi: '翅膀 · 赤红', sample: '翅，翅膀的翅' },
  'ch-u-1': { pinyin: 'chū', hanzi: '出门 · 出发 · 初升', sample: '出，出门的出' },
  'ch-u-2': { pinyin: 'chú', hanzi: '厨房 · 消除 · 除法', sample: '厨，厨房的厨' },
  'ch-u-3': { pinyin: 'chǔ', hanzi: '相处 · 处所', sample: '处' },
  'ch-u-4': { pinyin: 'chù', hanzi: '到处 · 触碰', sample: '处，到处的处' },
  'ch-ai-1': { pinyin: 'chāi', hanzi: '拆开 · 拆礼盒', sample: '拆，拆开的拆' },
  'ch-ai-2': { pinyin: 'chái', hanzi: '木柴 · 柴火', sample: '柴' },
  'ch-ui-1': { pinyin: 'chuī', hanzi: '吹风 · 吹泡泡', sample: '吹，吹泡泡的吹' },
  'ch-ui-2': { pinyin: 'chuí', hanzi: '锤子 · 捶背', sample: '锤，锤子的锤' },
  'ch-ao-1': { pinyin: 'chāo', hanzi: '超市 · 抄写 · 超过', sample: '超，超市的超' },
  'ch-ao-2': { pinyin: 'cháo', hanzi: '朝阳 · 鸟巢 · 朝代', sample: '朝，朝阳的朝' },
  'ch-ao-3': { pinyin: 'chǎo', hanzi: '吵闹 · 炒菜', sample: '炒，炒菜的炒' },
  'ch-ou-1': { pinyin: 'chōu', hanzi: '抽烟 · 抽纸 · 抽屉', sample: '抽，抽纸的抽' },
  'ch-ou-2': { pinyin: 'chóu', hanzi: '丝绸 · 愁眉', sample: '绸，丝绸的绸' },
  'ch-ou-3': { pinyin: 'chǒu', hanzi: '小丑 · 丑陋', sample: '丑，小丑的丑' },
  'ch-ou-4': { pinyin: 'chòu', hanzi: '臭气 · 臭味', sample: '臭' },
  'ch-an-1': { pinyin: 'chān', hanzi: '搀扶', sample: '搀' },
  'ch-an-2': { pinyin: 'chán', hanzi: '知了蝉鸣 · 缠绕', sample: '蝉，蝉鸣的蝉' },
  'ch-an-3': { pinyin: 'chǎn', hanzi: '铲子 · 产生', sample: '铲，铲子的铲' },
  'ch-an-4': { pinyin: 'chàn', hanzi: '颤抖 · 颤动', sample: '颤' },
  'ch-en-2': { pinyin: 'chén', hanzi: '灰尘 · 陈旧 · 早晨', sample: '尘，灰尘的尘' },
  'ch-en-4': { pinyin: 'chèn', hanzi: '衬衫 · 称心', sample: '衬，衬衫的衬' },
  'ch-ang-2': { pinyin: 'cháng', hanzi: '长短 · 经常 · 品尝', sample: '长，长短的长' },
  'ch-ang-3': { pinyin: 'chǎng', hanzi: '广场 · 操场 · 场地', sample: '场，操场的场' },
  'ch-ang-4': { pinyin: 'chàng', hanzi: '唱歌 · 歌唱', sample: '唱，唱歌的唱' },
  'ch-eng-1': { pinyin: 'chēng', hanzi: '称赞 · 撑伞', sample: '撑，撑伞的撑' },
  'ch-eng-2': { pinyin: 'chéng', hanzi: '成功 · 橙子 · 城市 · 诚实', sample: '成，成功的成' },
  'ch-ong-1': { pinyin: 'chōng', hanzi: '充满 · 冲锋', sample: '冲，充满的冲' },
  'ch-ong-2': { pinyin: 'chóng', hanzi: '昆虫 · 虫子', sample: '虫，昆虫的虫' },
  'ch-ong-3': { pinyin: 'chǒng', hanzi: '宠物 · 宠爱', sample: '宠，宠物的宠' },

  // sh
  'sh-a-1': { pinyin: 'shā', hanzi: '沙滩 · 沙发 · 风沙', sample: '沙，沙发的沙' },
  'sh-a-3': { pinyin: 'shǎ', hanzi: '傻笑 · 傻乎乎', sample: '傻' },
  'sh-a-4': { pinyin: 'shà', hanzi: '大厦 · 霎时', sample: '厦' },
  'sh-e-1': { pinyin: 'shē', hanzi: '奢侈', sample: '奢' },
  'sh-e-2': { pinyin: 'shé', hanzi: '小蛇 · 蛇年', sample: '蛇，小蛇的蛇' },
  'sh-e-3': { pinyin: 'shě', hanzi: '舍得 · 舍弃', sample: '舍' },
  'sh-e-4': { pinyin: 'shè', hanzi: '宿舍 · 社会 · 设计', sample: '社，社会的社' },
  'sh-i-1': { pinyin: 'shī', hanzi: '老师 · 狮子 · 古诗', sample: '师，老师的师' },
  'sh-i-2': { pinyin: 'shí', hanzi: '数字十 · 时间 · 石头', sample: '十，数字十的十' },
  'sh-i-3': { pinyin: 'shǐ', hanzi: '历史 · 开始 · 使用', sample: '史，历史的史' },
  'sh-i-4': { pinyin: 'shì', hanzi: '世界 · 事情 · 城市', sample: '世，世界的世' },
  'sh-u-1': { pinyin: 'shū', hanzi: '读书 · 叔叔 · 书包', sample: '书，读书的书' },
  'sh-u-2': { pinyin: 'shú', hanzi: '成熟 · 熟人', sample: '熟，成熟的熟' },
  'sh-u-3': { pinyin: 'shǔ', hanzi: '数数 · 老鼠 · 暑假', sample: '鼠，小老鼠的鼠' },
  'sh-u-4': { pinyin: 'shù', hanzi: '大树 · 数字 · 数量', sample: '树，大树的树' },
  'sh-ai-1': { pinyin: 'shāi', hanzi: '筛子 · 筛选', sample: '筛' },
  'sh-ai-4': { pinyin: 'shài', hanzi: '晒太阳 · 晾晒', sample: '晒，晒太阳的晒' },
  'sh-ui-2': { pinyin: 'shuí', hanzi: '谁呀 · 是谁', sample: '谁，谁呀的谁' },
  'sh-ui-3': { pinyin: 'shuǐ', hanzi: '喝水 · 雨水 · 水果', sample: '水，喝水的水' },
  'sh-ui-4': { pinyin: 'shuì', hanzi: '睡觉 · 睡梦', sample: '睡，睡觉的睡' },
  'sh-ao-1': { pinyin: 'shāo', hanzi: '烧烤 · 燃烧 · 捎带', sample: '烧，烧烤的烧' },
  'sh-ao-2': { pinyin: 'sháo', hanzi: '勺子 · 汤勺', sample: '勺，勺子的勺' },
  'sh-ao-3': { pinyin: 'shǎo', hanzi: '多少 · 很少 · 少女', sample: '少，多少的少' },
  'sh-ao-4': { pinyin: 'shào', hanzi: '少年 · 口哨', sample: '哨，口哨的哨' },
  'sh-ou-1': { pinyin: 'shōu', hanzi: '收获 · 收集 · 收拾', sample: '收，收获的收' },
  'sh-ou-3': { pinyin: 'shǒu', hanzi: '双手 · 手心 · 手表', sample: '手，双手的' },
  'sh-ou-4': { pinyin: 'shòu', hanzi: '小瘦 · 长寿 · 受伤', sample: '寿，长寿的寿' },
  'sh-an-1': { pinyin: 'shān', hanzi: '大山 · 扇子 · 山羊', sample: '山，大山的山' },
  'sh-an-3': { pinyin: 'shǎn', hanzi: '闪电 · 闪闪发光', sample: '闪，闪电的闪' },
  'sh-an-4': { pinyin: 'shàn', hanzi: '善良 · 扇子 · 妥善', sample: '善，善良的善' },
  'sh-en-1': { pinyin: 'shēn', hanzi: '身体 · 伸出手 · 深浅', sample: '身，身体的身' },
  'sh-en-2': { pinyin: 'shén', hanzi: '什么 · 神奇 · 神仙', sample: '神，神奇的神' },
  'sh-en-3': { pinyin: 'shěn', hanzi: '婶婶 · 审查', sample: '婶，婶婶的婶' },
  'sh-ang-1': { pinyin: 'shāng', hanzi: '受伤 · 商量 · 商店', sample: '商，商店的商' },
  'sh-ang-3': { pinyin: 'shǎng', hanzi: '欣赏 · 赏月', sample: '赏，赏月的赏' },
  'sh-ang-4': { pinyin: 'shàng', hanzi: '上学 · 上面 · 早上', sample: '上，上学的上' },
  'sh-eng-1': { pinyin: 'shēng', hanzi: '声音 · 生长 · 升旗', sample: '生，声音的声' },
  'sh-eng-2': { pinyin: 'shéng', hanzi: '绳子 · 跳绳', sample: '绳，跳绳的绳' },
  'sh-eng-3': { pinyin: 'shěng', hanzi: '节省 · 省份', sample: '省，节省的省' },
  'sh-eng-4': { pinyin: 'shèng', hanzi: '胜利 · 盛开', sample: '胜，胜利的胜' },

  // r
  'r-e-4': { pinyin: 'rè', hanzi: '天气热 · 热情', sample: '热，天气热的热' },
  'r-i-4': { pinyin: 'rì', hanzi: '日月 · 日出 · 生日', sample: '日，生日的日' },
  'r-u-2': { pinyin: 'rú', hanzi: '如果 · 比如', sample: '如，如果的如' },
  'r-u-4': { pinyin: 'rù', hanzi: '进入 · 入门 · 出入', sample: '入，进入的入' },
  'r-ui-4': { pinyin: 'ruì', hanzi: '瑞士 · 祥瑞 · 聪明睿智', sample: '瑞' },
  'r-ao-2': { pinyin: 'ráo', hanzi: '饶恕 · 求饶', sample: '饶' },
  'r-ao-3': { pinyin: 'rǎo', hanzi: '打扰 · 骚扰', sample: '扰' },
  'r-ao-4': { pinyin: 'rào', hanzi: '绕圈 · 围绕', sample: '绕，绕圈的绕' },
  'r-ou-2': { pinyin: 'róu', hanzi: '柔软 · 揉眼睛', sample: '柔，柔软的柔' },
  'r-ou-4': { pinyin: 'ròu', hanzi: '吃肉 · 牛肉 · 肌肉', sample: '肉，吃肉的肉' },
  'r-an-2': { pinyin: 'rán', hanzi: '然后 · 当然 · 燃烧', sample: '然，然后的然' },
  'r-an-3': { pinyin: 'rǎn', hanzi: '染色 · 污染', sample: '染，染色的染' },
  'r-en-2': { pinyin: 'rén', hanzi: '人类 · 好人 · 人民', sample: '人，好人的人' },
  'r-en-3': { pinyin: 'rěn', hanzi: '忍耐 · 忍受', sample: '忍' },
  'r-en-4': { pinyin: 'rèn', hanzi: '认真 · 认识 · 任务', sample: '认，认真的认' },
  'r-ang-3': { pinyin: 'rǎng', hanzi: '土壤 · 大嚷', sample: '壤，土壤的壤' },
  'r-ang-4': { pinyin: 'ràng', hanzi: '让座 · 礼让', sample: '让，让座的让' },
  'r-eng-1': { pinyin: 'rēng', hanzi: '扔掉 · 扔球', sample: '扔，扔球的扔' },
  'r-eng-2': { pinyin: 'réng', hanzi: '仍然 · 仍旧', sample: '仍' },
  'r-ong-2': { pinyin: 'róng', hanzi: '光荣 · 羽绒服 · 容易', sample: '荣，光荣的荣' },

  // z
  'z-a-1': { pinyin: 'zā', hanzi: '扎紧 · 包扎', sample: '扎' },
  'z-a-2': { pinyin: 'zá', hanzi: '杂技 · 复杂', sample: '杂，杂技的杂' },
  'z-e-2': { pinyin: 'zé', hanzi: '选择 · 责任 · 原则', sample: '择，选择的择' },
  'z-i-1': { pinyin: 'zī', hanzi: '姿势 · 资源 · 滋味', sample: '姿，姿势的姿' },
  'z-i-3': { pinyin: 'zǐ', hanzi: '儿子 · 紫色 · 种子', sample: '紫，紫色的紫' },
  'z-i-4': { pinyin: 'zì', hanzi: '汉字 · 写字 · 自己', sample: '字，汉字的字' },
  'z-u-1': { pinyin: 'zū', hanzi: '出租车 · 租房', sample: '租，出租车的租' },
  'z-u-2': { pinyin: 'zú', hanzi: '足球 · 民族 · 足够', sample: '足，足球的足' },
  'z-u-3': { pinyin: 'zǔ', hanzi: '祖国 · 爷爷祖先 · 小组', sample: '祖，祖国的祖' },
  'z-ai-1': { pinyin: 'zāi', hanzi: '栽树 · 灾难', sample: '栽，栽树的栽' },
  'z-ai-3': { pinyin: 'zǎi', hanzi: '宰相 · 牛仔裤', sample: '仔' },
  'z-ai-4': { pinyin: 'zài', hanzi: '再见 · 现在 · 在家', sample: '在，在家的在' },
  'z-ui-3': { pinyin: 'zuǐ', hanzi: '嘴巴 · 嘴角', sample: '嘴，嘴巴的嘴' },
  'z-ui-4': { pinyin: 'zuì', hanzi: '最好 · 最初 · 罪恶', sample: '最，最好的最' },
  'z-ao-1': { pinyin: 'zāo', hanzi: '糟糕 · 遭受', sample: '糟，糟糕的糟' },
  'z-ao-3': { pinyin: 'zǎo', hanzi: '早晨 · 洗澡 · 早安', sample: '早，早上的早' },
  'z-ao-4': { pinyin: 'zào', hanzi: '做饭造纸 · 制造', sample: '造，制造的造' },
  'z-ou-3': { pinyin: 'zǒu', hanzi: '走路 · 行走', sample: '走，走路的走' },
  'z-ou-4': { pinyin: 'zòu', hanzi: '奏乐 · 演奏', sample: '奏，演奏的奏' },
  'z-an-1': { pinyin: 'zān', hanzi: '发簪', sample: '簪' },
  'z-an-3': { pinyin: 'zǎn', hanzi: '积攒 · 攒钱', sample: '攒' },
  'z-an-4': { pinyin: 'zàn', hanzi: '赞美 · 赞成 · 称赞', sample: '赞，赞美的赞' },
  'z-en-3': { pinyin: 'zěn', hanzi: '怎么 · 怎样', sample: '怎，怎么的怎' },
  'z-ang-1': { pinyin: 'zāng', hanzi: '肮脏 · 脏话', sample: '脏，肮脏的脏' },
  'z-eng-1': { pinyin: 'zēng', hanzi: '增加 · 增长', sample: '增，增加的增' },
  'z-eng-4': { pinyin: 'zèng', hanzi: '赠送 · 赠品', sample: '赠，赠送的赠' },
  'z-ong-1': { pinyin: 'zōng', hanzi: '祖宗 · 棕色 · 追踪', sample: '棕，棕色的棕' },
  'z-ong-3': { pinyin: 'zǒng', hanzi: '总结 · 总理 · 总是', sample: '总，总结的总' },
  'z-ong-4': { pinyin: 'zòng', hanzi: '粽子 · 吃粽子', sample: '粽，粽子的粽' },

  // c
  'c-a-1': { pinyin: 'cā', hanzi: '擦黑板 · 擦手', sample: '擦，擦手的擦' },
  'c-e-4': { pinyin: 'cè', hanzi: '厕所 · 测试 · 册子', sample: '测，测试的测' },
  'c-i-1': { pinyin: 'cī', hanzi: '疵瑕', sample: '疵' },
  'c-i-2': { pinyin: 'cí', hanzi: '磁铁 · 词语 · 慈祥', sample: '磁，磁铁的磁' },
  'c-i-3': { pinyin: 'cǐ', hanzi: '彼此 · 从此 · 此时', sample: '此' },
  'c-i-4': { pinyin: 'cì', hanzi: '刺猬 · 一次 · 刺激', sample: '刺，刺猬的刺' },
  'c-u-1': { pinyin: 'cū', hanzi: '粗细 · 粗壮', sample: '粗，粗细的粗' },
  'c-u-4': { pinyin: 'cù', hanzi: '吃醋 · 促进', sample: '醋，吃醋的醋' },
  'c-ai-1': { pinyin: 'cāi', hanzi: '猜谜语 · 猜测', sample: '猜，猜谜语的猜' },
  'c-ai-2': { pinyin: 'cái', hanzi: '刚才 · 木材 · 人才', sample: '才，刚才的才' },
  'c-ai-3': { pinyin: 'cǎi', hanzi: '采花 · 彩色 · 彩虹', sample: '彩，彩色的彩' },
  'c-ai-4': { pinyin: 'cài', hanzi: '青菜 · 蔬菜 · 菜单', sample: '菜，青菜的菜' },
  'c-ui-1': { pinyin: 'cuī', hanzi: '催促 · 催促', sample: '催，催促的催' },
  'c-ui-4': { pinyin: 'cuì', hanzi: '清脆 · 翡翠', sample: '翠，翡翠的翠' },
  'c-ao-1': { pinyin: 'cāo', hanzi: '做操 · 体操', sample: '操，做操的操' },
  'c-ao-2': { pinyin: 'cáo', hanzi: '水槽 · 曹操', sample: '曹' },
  'c-ao-3': { pinyin: 'cǎo', hanzi: '小草 · 花草 · 草原', sample: '草，小草的草' },
  'c-ou-4': { pinyin: 'còu', hanzi: '拼凑 · 凑合', sample: '凑' },
  'c-an-1': { pinyin: 'cān', hanzi: '参加 · 餐厅 · 餐桌', sample: '餐，餐厅的餐' },
  'c-an-2': { pinyin: 'cán', hanzi: '蚕豆 · 春蚕吐丝', sample: '蚕，春蚕的蚕' },
  'c-an-3': { pinyin: 'cǎn', hanzi: '惨烈 · 凄惨', sample: '惨' },
  'c-an-4': { pinyin: 'càn', hanzi: '灿烂 · 璀璨', sample: '灿，灿烂的灿' },
  'c-ang-1': { pinyin: 'cāng', hanzi: '船舱 · 苍白 · 苍蝇', sample: '舱，船舱的舱' },
  'c-ang-2': { pinyin: 'cáng', hanzi: '捉迷藏 · 宝藏', sample: '藏，捉迷藏的藏' },
  'c-eng-2': { pinyin: 'céng', hanzi: '曾经 · 楼层', sample: '层，楼层的层' },
  'c-ong-1': { pinyin: 'cōng', hanzi: '聪明 · 大葱 · 匆忙', sample: '聪，聪明的聪' },
  'c-ong-2': { pinyin: 'cóng', hanzi: '从前 · 草丛 · 服从', sample: '从，从前的从' },

  // s
  's-a-1': { pinyin: 'sā', hanzi: '撒手 · 撒娇', sample: '撒，撒手的撒' },
  's-a-3': { pinyin: 'sǎ', hanzi: '洒水 · 洒满草地', sample: '洒，洒水的洒' },
  's-e-4': { pinyin: 'sè', hanzi: '颜色 · 色彩 · 红色', sample: '色，颜色的色' },
  's-i-1': { pinyin: 'sī', hanzi: '司机 · 丝绸 · 思考', sample: '丝，丝绸的丝' },
  's-i-3': { pinyin: 'sǐ', hanzi: '死亡', sample: '死' },
  's-i-4': { pinyin: 'sì', hanzi: '数字四 · 四周 · 寺庙', sample: '四，数字四的四' },
  's-u-1': { pinyin: 'sū', hanzi: '复苏 · 江苏', sample: '苏' },
  's-u-2': { pinyin: 'sú', hanzi: '风俗 · 习俗', sample: '俗' },
  's-u-4': { pinyin: 'sù', hanzi: '速度 · 告诉 · 宿舍', sample: '速，速度的速' },
  's-ai-1': { pinyin: 'sāi', hanzi: '塞车 · 腮帮子', sample: '塞' },
  's-ai-4': { pinyin: 'sài', hanzi: '比赛 · 赛跑 · 赛车', sample: '赛，比赛的赛' },
  's-ui-1': { pinyin: 'suī', hanzi: '虽然 · 虽说', sample: '虽，虽然的虽' },
  's-ui-2': { pinyin: 'suí', hanzi: '跟随 · 随便 · 随手', sample: '随，跟随的随' },
  's-ui-4': { pinyin: 'suì', hanzi: '岁岁平安 · 年岁 · 碎了', sample: '岁，岁岁的岁' },
  's-ao-1': { pinyin: 'sāo', hanzi: '骚动', sample: '骚' },
  's-ao-3': { pinyin: 'sǎo', hanzi: '扫地 · 打扫 · 扫帚', sample: '扫，扫地的扫' },
  's-ou-1': { pinyin: 'sōu', hanzi: '搜索 · 一艘船', sample: '搜，搜索的搜' },
  's-ou-4': { pinyin: 'sòu', hanzi: '咳嗽', sample: '嗽，咳嗽的嗽' },
  's-an-1': { pinyin: 'sān', hanzi: '数字三 · 三只小猪', sample: '三，数字三的三' },
  's-an-3': { pinyin: 'sǎn', hanzi: '雨伞 · 散开', sample: '伞，雨伞的伞' },
  's-an-4': { pinyin: 'sàn', hanzi: '散步 · 分散', sample: '散，散步的散' },
  's-en-1': { pinyin: 'sēn', hanzi: '森林 · 森严', sample: '森，森林的森' },
  's-ang-1': { pinyin: 'sāng', hanzi: '桑树 · 蚕桑', sample: '桑，桑树的桑' },
  's-ang-3': { pinyin: 'sǎng', hanzi: '嗓子 · 嗓音', sample: '嗓，嗓子的嗓' },
  's-eng-1': { pinyin: 'sēng', hanzi: '僧人 · 和尚', sample: '僧' },
  's-ong-1': { pinyin: 'sōng', hanzi: '松树 · 轻松 · 宽松', sample: '松，松树的松' },
  's-ong-4': { pinyin: 'sòng', hanzi: '送给 · 背诵 · 赠送', sample: '送，送给的送' },

  // y
  'y-a-1': { pinyin: 'yā', hanzi: '小鸭子 · 压住', sample: '鸭，小鸭子的鸭' },
  'y-a-2': { pinyin: 'yá', hanzi: '牙齿 · 发芽 · 月牙', sample: '牙，牙齿的牙' },
  'y-a-3': { pinyin: 'yǎ', hanzi: '优雅 · 文雅', sample: '雅' },
  'y-a-4': { pinyin: 'yà', hanzi: '亚洲 · 大亚湾', sample: '亚' },
  'y-e-1': { pinyin: 'yē', hanzi: '椰子 · 椰树', sample: '椰，椰子的椰' },
  'y-e-2': { pinyin: 'yé', hanzi: '爷爷 · 祖爷', sample: '爷，爷爷的爷' },
  'y-e-3': { pinyin: 'yě', hanzi: '也许 · 野外 · 田野', sample: '野，田野的野' },
  'y-e-4': { pinyin: 'yè', hanzi: '树叶 · 夜晚 · 页面', sample: '叶，树叶的叶' },
  'y-i-1': { pinyin: 'yī', hanzi: '第一 · 衣服 · 医生', sample: '一，第一的一' },
  'y-i-2': { pinyin: 'yí', hanzi: '阿姨 · 移动', sample: '姨，阿姨的姨' },
  'y-i-3': { pinyin: 'yǐ', hanzi: '椅子 · 已经 · 蚂蚁', sample: '椅，椅子的椅' },
  'y-i-4': { pinyin: 'yì', hanzi: '意思 · 容易 · 意义', sample: '意，意思的意' },
  'y-u-1': { pinyin: 'yū', hanzi: '淤泥 · 迂回', sample: '淤' },
  'y-u-2': { pinyin: 'yú', hanzi: '小金鱼 · 钓鱼', sample: '鱼，小金鱼的鱼' },
  'y-u-3': { pinyin: 'yǔ', hanzi: '下雨 · 羽毛 · 语文', sample: '雨，下雨的雨' },
  'y-u-4': { pinyin: 'yù', hanzi: '玉米 · 教育 · 遇见', sample: '玉，玉米的玉' },
  'y-ao-1': { pinyin: 'yāo', hanzi: '要求 · 妖怪', sample: '要' },
  'y-ao-2': { pinyin: 'yáo', hanzi: '摇晃 · 摇篮', sample: '摇，摇晃的摇' },
  'y-ao-3': { pinyin: 'yǎo', hanzi: '咬一口 · 咬断', sample: '咬，咬一口的咬' },
  'y-ao-4': { pinyin: 'yào', hanzi: '重要 · 吃药 · 不要', sample: '要，重要的要' },
  'y-ou-1': { pinyin: 'yōu', hanzi: '优秀 · 优美', sample: '优，优秀的优' },
  'y-ou-2': { pinyin: 'yóu', hanzi: '游泳 · 游戏 · 邮票', sample: '游，游泳的游' },
  'y-ou-3': { pinyin: 'yǒu', hanzi: '朋友 · 友好 · 有无', sample: '友，朋友的友' },
  'y-ou-4': { pinyin: 'yòu', hanzi: '右手 · 幼儿园 · 又来', sample: '右，右手的右' },
  'y-üe-4': { pinyin: 'yuè', hanzi: '月亮 · 音乐 · 快乐', sample: '月，月亮的月' },
  'y-an-1': { pinyin: 'yān', hanzi: '烟花 · 咽喉', sample: '烟，烟花的烟' },
  'y-an-2': { pinyin: 'yán', hanzi: '颜色 · 岩石 · 食盐', sample: '颜，颜色的颜' },
  'y-an-3': { pinyin: 'yǎn', hanzi: '眼睛 · 表演 · 眼泪', sample: '眼，眼睛的眼' },
  'y-an-4': { pinyin: 'yàn', hanzi: '大雁 · 燕子 · 实验', sample: '燕，小燕子的燕' },
  'y-in-1': { pinyin: 'yīn', hanzi: '音乐 · 声音 · 阴天', sample: '音，音乐的音' },
  'y-in-2': { pinyin: 'yín', hanzi: '银行 · 银白', sample: '银，银行的银' },
  'y-in-3': { pinyin: 'yǐn', hanzi: '吸引 · 饮料', sample: '引' },
  'y-in-4': { pinyin: 'yìn', hanzi: '脚印 · 印章 · 打印', sample: '印，脚印的印' },
  'y-ang-1': { pinyin: 'yāng', hanzi: '中央 · 秧苗', sample: '秧' },
  'y-ang-2': { pinyin: 'yáng', hanzi: '太阳 · 小羊 · 海洋', sample: '阳，太阳的阳' },
  'y-ang-3': { pinyin: 'yǎng', hanzi: '养成 · 仰望', sample: '养' },
  'y-ang-4': { pinyin: 'yàng', hanzi: '样子 · 榜样', sample: '样，样子的样' },
  'y-ing-1': { pinyin: 'yīng', hanzi: '老鹰 · 应该 · 英雄', sample: '鹰，老鹰的鹰' },
  'y-ing-2': { pinyin: 'yíng', hanzi: '萤火虫 · 欢迎 · 赢得', sample: '萤，萤火虫的萤' },
  'y-ing-3': { pinyin: 'yǐng', hanzi: '影子 · 电影', sample: '影，电影的影' },
  'y-ing-4': { pinyin: 'yìng', hanzi: '硬币 · 答应', sample: '硬，硬币的硬' },
  'y-ong-1': { pinyin: 'yōng', hanzi: '拥抱 · 拥挤', sample: '拥，拥抱的拥' },
  'y-ong-3': { pinyin: 'yǒng', hanzi: '勇敢 · 游泳', sample: '勇，勇敢的勇' },
  'y-ong-4': { pinyin: 'yòng', hanzi: '使用 · 用心 · 作用', sample: '用，使用的用' },

  // w
  'w-a-1': { pinyin: 'wā', hanzi: '青蛙 · 娃娃 · 挖土', sample: '蛙，青蛙的蛙' },
  'w-a-2': { pinyin: 'wá', hanzi: '娃娃 · 布娃娃', sample: '娃，布娃娃的娃' },
  'w-a-3': { pinyin: 'wǎ', hanzi: '瓦片 · 砖瓦', sample: '瓦' },
  'w-a-4': { pinyin: 'wà', hanzi: '袜子 · 穿袜子', sample: '袜，袜子的袜' },
  'w-o-1': { pinyin: 'wō', hanzi: '鸟窝 · 酒窝', sample: '窝，小鸟窝的窝' },
  'w-o-3': { pinyin: 'wǒ', hanzi: '我们 · 我家 · 我爱学习', sample: '我，我们的我' },
  'w-o-4': { pinyin: 'wò', hanzi: '握手 · 卧室', sample: '握，握手的握' },
  'w-u-1': { pinyin: 'wū', hanzi: '乌鸦 · 房屋 · 屋顶', sample: '乌，乌鸦的乌' },
  'w-u-2': { pinyin: 'wú', hanzi: '无敌 · 没有 · 无数', sample: '无，无敌的无' },
  'w-u-3': { pinyin: 'wǔ', hanzi: '数字五 · 跳舞 · 武器', sample: '五，数字五的五' },
  'w-u-4': { pinyin: 'wù', hanzi: '大雾 · 植物 · 任务', sample: '雾，大雾的雾' },
  'w-ai-1': { pinyin: 'wāi', hanzi: '歪斜 · 歪歪扭扭', sample: '歪' },
  'w-ai-4': { pinyin: 'wài', hanzi: '外公 · 外面 · 外婆', sample: '外，外面的外' },
  'w-ei-1': { pinyin: 'wēi', hanzi: '微笑 · 危险 · 威武', sample: '微，微笑的微' },
  'w-ei-2': { pinyin: 'wéi', hanzi: '围巾 · 为了 · 围绕', sample: '围，围巾的围' },
  'w-ei-3': { pinyin: 'wěi', hanzi: '伟大 · 尾巴', sample: '尾，尾巴的尾' },
  'w-ei-4': { pinyin: 'wèi', hanzi: '味道 · 因为 · 位置', sample: '味，味道的味' },
  'w-an-1': { pinyin: 'wān', hanzi: '弯曲 · 台湾 · 海湾', sample: '弯，弯弯的弯' },
  'w-an-2': { pinyin: 'wán', hanzi: '玩具 · 玩耍 · 完成', sample: '玩，玩玩具的玩' },
  'w-an-3': { pinyin: 'wǎn', hanzi: '小碗 · 晚上 · 早晚', sample: '晚，晚上的晚' },
  'w-an-4': { pinyin: 'wàn', hanzi: '一万 · 千万 · 万里', sample: '万，一万的万' },
  'w-en-1': { pinyin: 'wēn', hanzi: '温暖 · 温度 · 温柔', sample: '温，温暖的温' },
  'w-en-2': { pinyin: 'wén', hanzi: '新闻 · 文化 · 闻一闻', sample: '文，文化的文' },
  'w-en-3': { pinyin: 'wěn', hanzi: '稳当 · 亲吻', sample: '吻，亲吻的吻' },
  'w-en-4': { pinyin: 'wèn', hanzi: '提问 · 问题 · 请问', sample: '问，提问的问' },
  'w-ang-1': { pinyin: 'wāng', hanzi: '小狗汪汪叫 · 水汪汪', sample: '汪，汪汪叫的汪' },
  'w-ang-2': { pinyin: 'wáng', hanzi: '国王 · 大王 · 狮子王', sample: '王，国王的王' },
  'w-ang-3': { pinyin: 'wǎng', hanzi: '网络 · 来往 · 渔网', sample: '网，网络的网' },
  'w-ang-4': { pinyin: 'wàng', hanzi: '忘记 · 希望 · 望远镜', sample: '望，希望的望' },
  'w-eng-1': { pinyin: 'wēng', hanzi: '老翁 · 蜜蜂嗡嗡叫', sample: '翁，老翁的翁' },
}
